### ISSUE TITLE
icon block component

### ISSUE THREAD

**Issue by AlishaOber** [SU-SWS/decanter#103]
Based on the name, this is the same as what UComm is calling "info blocks". 
![screen shot 2018-04-20 at 2 29 09 pm](https://user-images.githubusercontent.com/33696009/39074683-463cb7c2-44a7-11e8-9558-32bb355daa23.png)

**Note**: This exists in Redwood.

**Comment by sherakama** [comment]
Implemented in redwood theme.

**Comment by buttonwillowsix** [comment]
"Icon Block"

**Comment by buttonwillowsix** [comment]
Discussion:
Blocks for groups of links(info block) vs. block with content/stories (postcards)
Calling in Icon Block

**Comment by buttonwillowsix** [comment]
This ticket is closed in favor of a new approach, outlined here:

https://docs.google.com/document/d/1BVBr71fxqSEzxP-yb3MAQ_5Dm2i9bY9KydJZfV_Aaxk/edit#

and which is broken out:

- https://github.com/SU-SWS/decanter/issues/436
- https://github.com/SU-SWS/decanter/issues/435
- https://github.com/SU-SWS/decanter/issues/434
- https://github.com/SU-SWS/decanter/issues/437
- https://github.com/SU-SWS/decanter/issues/431
- https://github.com/SU-SWS/decanter/issues/430
