### ISSUE TITLE
Upgrade Bourbon to > 5.0.0 and refactor deprecated code.

### ISSUE THREAD

**Issue by josephgknox** [SU-SWS/decanter#112]

**Comment by JBCSU** [comment]
Thanks for taking this on, @josephgknox. Just to manage my expectation, when do you think this might be ready to merge? Days, weeks, months, or years ( ;) ) ?

**Comment by JBCSU** [comment]
Oh. Nevermind. I see you've had a PR open for days, and I just missed it. I'm reviewing it now.
