### ISSUE TITLE
Create video component (twig & sass)

### ISSUE THREAD

**Issue by sherakama** [SU-SWS/decanter#137]

**Comment by sherakama** [comment]
This is support for a responsive video handler on 3rd party videos. `<embed>` or `<iframes>`

**Comment by sherakama** [comment]
Possible for overlay text or images and/or captions.

**Comment by buttonwillowsix** [comment]
Include existing responsive embed component.

**Comment by sherakama** [comment]
Possible to re-use the responsive embed element.

**Comment by yvonnetangsu** [comment]
Done - .su-media
