### ISSUE TITLE
namespace rollup files

### ISSUE THREAD

**Issue by kgcreative** [SU-SWS/decanter#15]
During integration, sometimes it's hard to know whether you are pulling a file from your own library, or from Decanter's. Refactor rollups to include decanter namespace.

**Comment by sherakama** [comment]
hmm. interesting. 

Perhaps when we add our includes paths we only add 'node_modules' and not the full path to decanter. So to get everything your import would be:

```
@import 'decanter/decanter';
```

and to get at portions it would be

```
@import 'decanter/core/utilities/utilities';
```

**Comment by sherakama** [comment]
This would be versus what we have when our include paths are set to 'node_modules/decanter'

eg:
```
@import 'decanter';
@import 'core/utilities/utilities';
```

**Comment by kgcreative** [comment]
I thought about that, but that has other implications. This allows us to namespace rollups, without having to remove underscores. So any '_decanter-*' file we know is a rollup, and doesn't contain actual funtionality, plus, when importing, this makes it clearer when you are calling a decanter-specific rollup versus your own.

I'm ok with actual mixins, base files, functions, etc not being namespaced, but namespacing the rollup files gives us much more flexibility when developing.

**Comment by kgcreative** [comment]
(there's something that feels dangerous about adding npm path to our scss import paths, vs adding individual components, but I haven't quite figured out what.)

**Comment by sherakama** [comment]
From what I have seen a number of projects are using this: http://eyeglass.rocks/

I haven't fully grokked it yet but this seems to be a standard or convention for managing node modules in sass.

**Comment by kgcreative** [comment]
I believe both bourbon and neat can be eyeglass modules. I haven't quite grokked it yet, so i've been kicking that can down the road, since I don't want to add too much weight to our libraries

**Comment by kgcreative** [comment]
(this can be closed)
