### ISSUE TITLE
Create global footer component

### ISSUE THREAD

**Issue by sherakama** [SU-SWS/decanter#151]
Create a component for the global footer.

**Comment by JBCSU** [comment]
Markup and links to CSS can be found on Stanford's Identity site, specifically http://identity.stanford.edu/web-mobile.html#build-something-new .

**Comment by sherakama** [comment]
Responsive breakpoints
wrapping
sizes
spacing

All need review.

**Comment by annawatt** [comment]
Feedback from Yvonne  on our 12/19 check in: would like to improve some of the responsive styling as it does not match what is currently on the main home site footer. Can pick this up in the new year

**Comment by stocker** [comment]
@yvonnetangsu assigned this to me to look at making the global footer layout and styling match what we have on stanford.edu.

**Comment by sherakama** [comment]
@stocker Please close this if you are content with the current version of the footer.

**Comment by sherakama** [comment]
Done
