### ISSUE TITLE
Upgrade Neat to 3.0

### ISSUE THREAD

**Issue by JBCSU** [SU-SWS/decanter#159]
Assuming upgrading to Neat 3.0 (#158) is not a significantly bigger deal than upgrading to 2.1 (#155), please upgrade Neat to 3.0.

**Comment by bixgomez** [comment]
I did this work in the context of #161:
https://github.com/SU-SWS/decanter/tree/decanter-161-page-layout--3-column

**Comment by josephgknox** [comment]
Neat is gone.
