### ISSUE TITLE
Chrome review: Discovery.

### ISSUE THREAD

**Issue by sherakama** [SU-SWS/decanter#160]
Review Decanter with @jgknox to identify which of the following base design elements are already represented in Decanter as specified in the [Stanford Design Library](https://www.figma.com/file/gCGDmlyhKJ88zLvVcoUBYjjK/UComm-Design-Library?node-id=0%3A1) document in Figma:

- Typography
- Spacing
- Colors
- Shadows and Shapes

Please create tickets for any of the above items that aren't already correctly implemented in Decanter. Note that the work on the grid already has a ticket, #168. Note also that Iconography depends on FontAwesome, and we've pulled FA out of Decanter. We'll have to decide about that later.

**Comment by JBCSU** [comment]
This is probably a fine early ticket to assign to Yvonne, so let's hold off on this.

**Comment by yvonnetangsu** [comment]
Google doc with my base review notes:
https://docs.google.com/document/d/1UTRmbarBQFbmz1n-UZ1Jf3gyfxtXyjXHtKB_Rx-IY-I/edit?usp=sharing
