### ISSUE TITLE
Page Layout: 3 column

### ISSUE THREAD

**Issue by sherakama** [SU-SWS/decanter#161]
Create the 3 column mobile responsive layout as found in: https://www.figma.com/file/GytUeUKUtlYFdSkOBdVhJUKy/Interior-Pages

**Comment by JBCSU** [comment]
JIRA ticket [UCP-486](https://stanfordits.atlassian.net/browse/UCP-486)

**Comment by bixgomez** [comment]
I did this work in the context of #161:
https://github.com/SU-SWS/decanter/tree/decanter-161-page-layout--3-column
