### ISSUE TITLE
Page Layout: Right Sidebar

### ISSUE THREAD

**Issue by sherakama** [SU-SWS/decanter#162]
Create the 2 column right sidebar mobile responsive layout as found in: https://www.figma.com/file/GytUeUKUtlYFdSkOBdVhJUKy/Interior-Pages

**Comment by JBCSU** [comment]
JIRA ticket [UCP-485](https://stanfordits.atlassian.net/browse/UCP-485)

**Comment by bixgomez** [comment]
I did this work in the context of #161:
https://github.com/SU-SWS/decanter/tree/decanter-161-page-layout--3-column
