### ISSUE TITLE
Page Layout: Single column centered

### ISSUE THREAD

**Issue by sherakama** [SU-SWS/decanter#164]
Create the **Page: 1 column** layout as found in the [Interior Pages document in Figma](https://www.figma.com/file/GytUeUKUtlYFdSkOBdVhJUKy/Interior-Pages).

**Comment by JBCSU** [comment]
JIRA ticket [UCP-483 - Decanter: Implement single column page layout](https://stanfordits.atlassian.net/browse/UCP-483)

**Comment by bixgomez** [comment]
I did this work in the context of #161:
https://github.com/SU-SWS/decanter/tree/decanter-161-page-layout--3-column
