### ISSUE TITLE
Add all 5 breakpoints re: new figma design specs

### ISSUE THREAD

**Issue by sherakama** [SU-SWS/decanter#168]
Add all breakpoints documented in the two elements labeled **Responsive Notes** in the [Stanford Design Library document in Figma](https://www.figma.com/file/gCGDmlyhKJ88zLvVcoUBYjjK/UComm-Design-Library?node-id=0%3A1).

**Comment by JBCSU** [comment]
JIRA ticket [UCP-482 - Decanter: Add all breakpoints](https://stanfordits.atlassian.net/browse/UCP-482)

**Comment by bixgomez** [comment]
I did this work in the context of #161:
https://github.com/SU-SWS/decanter/tree/decanter-161-page-layout--3-column
