### ISSUE TITLE
File Naming conventions

### ISSUE THREAD

**Issue by kgcreative** [SU-SWS/decanter#18]
This is something I noticed as i've been using neat much more extensively, and I think it's a pattern we can replicate.

_underscore variables, functions and mixins are meant to be private, and called from inside other functions/mixins. (Not file names, but the name of the actual mixin.)

For example:

the `color` function, calls a `retrieve-color` function.
This second function should be `_retrieve-color`.

If any mixins need internal variables, they should be _underscored.

This creates a system where, `$variable`, `@mixin name()`, `@function name()` are all intended to be used and called outside of decanter, while `$_variable`, `@mixin _name()` and `@function _name()`  are all either called programatically, or used by our mixins. This helps us as developers to know what's intended to be called by the user, vs what we have available to use internally

**Comment by sherakama** [comment]
I've seen that convention used in other systems. I would be happy to implement the underscore naming scheme for intended private functions and mixins while keeping the full name for public.

**Comment by kgcreative** [comment]
I'm looking through some of my own work as a result of this, need to refactor some mixin settings as a result as well. I think this will be good in the long run. I also want to maintain parity with bourbon and neat as much as possible, especially when dealing with grids, since that will significantly improve outcomes

**Comment by sherakama** [comment]
👍
