### ISSUE TITLE
Update Button component

### ISSUE THREAD

**Issue by josephgknox** [SU-SWS/decanter#188]
- Add more padding bottom to optically align text in button (currently text is sinking) 
- Double check that there is no letter spacing
- We’ll want to revisit our margins around the button

**Comment by josephgknox** [comment]
<img width="220" alt="atom_button" src="https://user-images.githubusercontent.com/8933670/44177244-de9fe600-a0a1-11e8-964f-8c9f241a0311.png">

**Comment by sherakama** [comment]
@josephgknox what is there left to do on this?

**Comment by josephgknox** [comment]
@sherakama looks like more padding was never added to the bottom of the button's content for better optical alignment. Here is the world's smallest PR: https://github.com/SU-SWS/decanter/pull/287

We can close this ticket once merged.
