### ISSUE TITLE
Right-size breakpoints and sections

### ISSUE THREAD

**Issue by kgcreative** [SU-SWS/decanter#19]
in Homesite, we have three possible content widths: `edge-to-edge`, `full`, and `content`. - Those correspond, at XL breakpoints, to a "max-width" container, a smaller inset size for centered content (like news stories, or pages, without a side bar), and, edge-to-edge should be fairly self-explanatory.

I've also pretty much extended a modified version of bootstrap's breakpoints.
(xs, sm, md, lg, xl), with min, max, and 'only' variants to give us flexibility when implementing complex responsive design patters.

The breakpoints variable file also has a corresponding "sections" file, that map responsive behavior of content widths to breakpoints, to allow the centered section mixin to be able to programatically run through and automagically create sections as needed.

While all of those are configurable, the question is how opinionated we want to be in Decanter regarding those. Is that a good set of defaults? Should we provide more? less? other?

This is one of the more potentially complex aspects of the framework to document, explain, and implement, but I feel that once we have a good handle of it, it will make building complex layouts a breeze.

**Comment by sherakama** [comment]
We can be opinionated as we want to be with these default variables. Our functions and mixins will require everything they need to work to be sent to them through a parameter. We will not include global variables in our functions and mix ins. This way we can create all the wonderful and sensible (to us) variable defaults and use them with our functions and mixins and other can send in theirs. 

In the example I am putting together, I refactored the centered-section mixin to require just one section map to be passed through: https://github.com/SU-SWS/decanter/blob/aff8f3877b3fdf1078b9cbafe5226623bc7b432e/core/utilities/mixins/_centered-section.scss#L6

So in my work I can use the full, edge, or content maps by calling map-get on the $section variable or I could just create my own on the spot.
https://github.com/SU-SWS/decanter/pull/21/files#diff-26e546128596673c0548c127eedef129R11

I want to include a good deal of sensible and opinionated defaults in this library of work.

**Comment by kgcreative** [comment]
yeah, I like the way you are refactoring centered section. I'm in the middle of refactoring it again. That mixin needs to be split into two (following neat's convention of single-function mixins)

1) centered-container -- this one you just pass it the settings raw
2) responsive-container -- this one you pass a map.

I'm also refactoring the section maps to instead of having one giant nested map, you create one map per responsive set. This is less complex and works similarly to neat's grid-media mixin. Stay tuned.

As i've been working with neat a lot more, then only default global variable they consistently call is the $neat-grid; map, which is set by default, and is user overridable. I think that provides a default fallback that can be really nice, and something we can safely emulate

Stay tuned...

**Comment by kgcreative** [comment]
https://github.com/SU-SWS/decanter/pull/23 Addresses all of the above.

by refactoring `centered-section` to `centered-container` i was able to remove all the cruft

with a much more targeted `centered-container` mixin, i was able to create a `responsive-container` mixin that simply consumes a map.

I thought about making `responsive-container` work similar to the color map, but in this instance, we want our responsive sections to ONLY output the custom sections we specify. So that simplified things even more.
