### ISSUE TITLE
Complete Sidenav Component

### ISSUE THREAD

**Issue by josephgknox** [SU-SWS/decanter#192]
- Spacing around typography needs refinement, requires workshop with designers
- Vertical pipe belongs to the active page

Source file: https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Stanford-Design-Library?node-id=1%3A31

**Comment by sherakama** [comment]
Needs source update.

**Comment by sherakama** [comment]
Dupe #76
