### ISSUE TITLE
Implement typography levels

### ISSUE THREAD

**Issue by josephgknox** [SU-SWS/decanter#199]
- Make this: https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Stanford-Design-Library?node-id=1%3A16

**Comment by sherakama** [comment]
Create and establish both mixins and default element styles for all of the level headings identified in the source Figma design file.

**Comment by buttonwillowsix** [comment]
Closing this issue in favor of it's twin: https://github.com/SU-SWS/decanter/pull/245
