### ISSUE TITLE
Create Image with Caption component

### ISSUE THREAD

**Issue by josephgknox** [SU-SWS/decanter#200]

**Comment by josephgknox** [comment]
<img width="627" alt="molecule_image-and-caption" src="https://user-images.githubusercontent.com/8933670/44177580-6b976f00-a0a3-11e8-8584-8ceecea6e700.png">

**Comment by sherakama** [comment]
@josephgknox is this still a thing to make?

**Comment by josephgknox** [comment]
This was one of the original patterns from @kerri-augenstein's Google Draw. Perhaps she can add a note about whether or not this is still something that we want to build out (now or in the future).

**Comment by josephgknox** [comment]
This is still a thing (following up on previous comments). :)

**Comment by yvonnetangsu** [comment]
Done .su-media
