### ISSUE TITLE
Create Date Stacked component

### ISSUE THREAD

**Issue by josephgknox** [SU-SWS/decanter#201]

**Comment by josephgknox** [comment]
<img width="215" alt="atom_date-stacked" src="https://user-images.githubusercontent.com/8933670/44177645-ab5e5680-a0a3-11e8-9596-e737a3086835.png">

**Comment by sherakama** [comment]
Scott wants it, Joe and Mike have it.

**Comment by sherakama** [comment]
Needs refactoring. Please connect to work on it.

**Comment by buttonwillowsix** [comment]
Yvonne confirms this work is in master.
