### ISSUE TITLE
Ems, Rems, and Pixels, Oh My!

### ISSUE THREAD

**Issue by kgcreative** [SU-SWS/decanter#22]
I noticed you were resetting your body to 1em, so I wanted to give you a bit of insight regarding my decisions for font sizes.

REM units are calculated from the Root element of your document. This is the `<html>` element.
EM units are calculated from the EM element's parent (so in this case, if we set an em font-size on `<body>`, that size is calculated from the HTML parent.

In most browsers, the default font size is 16px. Most people, then, set a font size of 1em, or 100% on body.

In order to be sensitive to folks who may need larger font sizes for accessibility reasons, I prefer not to use any px units when declaring font sizes.

However, I find it a pain in the ass to have to constantly be dividing by 1.6 in order to figure out px -> rem conversions.

So:

$root-font-size: 10px (I set this so when I use the `rem(16px)` function from the unit conversion mixin, it calculates me down to 1.6rem) Most of the time, I don't really even need that. I know if I say `font-size: 1.6rem` that is equal to `font-size: 16px`.

Now, if I were to say:
`html { font-size: $root-font-size }` - that would technically do that for me.

However, because I want to be respectful of people who change their default browser font size (generally because they have accessibility needs) - Instead, I say:
`html { font-size: 62.5% }`

This means for 90% of users, html = 10px.

But, I don't want that for my responsive typography units. The CSS world pretty much exists in a 1em = 16px convention.

So.

Next, we have
`$base-font-size: 16px`
`body { font-size: em($base-font-size, $root-font-size) }`

Which gives us an equivalent of: `body { font-size: 1.6em }` (that is: 16px / 10px = 1.6) 

$base-font-size is also the variable that them em() function uses in order to do px to em calculations.

With that set, then we can say:
`p {font-size: modular-scale(0);}` (equivalent to `font-size: 1em`)

and

`p3 {font-size: modular-scale(3);}` (equivalent to `font-size: 1.953125 em` -or- `font-size: 31.25px`, -or- `16px * 1.25 * 1.25 * 1.25`)

We configured the modular scale increment in `bourbon-settings`, and in our case, we're using a 1.25 multiplier modular scale to proportionally grow and shrink all our fonts, as well as vertical rythm

What are the implications of this?

Well, we could, for example, set all our sizings, proportions, spacing, etc to be ideal in our LG breakpoint.

This gives us the minimal:
```
$root-font-size: 10px;
$base-font-size: 16px;

html {
  font-size: 62.5%; // proportionally equivalent to 10px
}

body {
  font-size: em($base-font-size, $root-font-size);
}
```

In the more advanced side of things, we can do something like:
```
$root-font-size: 10px;
$base-font-size: 18px;

html {
  font-size: 62.5%; // proportionally equivalent to 10px
}

body {
  @include grid-media($media-sm-max) {
    font-size: 1.6em; // 10px * 1.6em = 16px
  }
  @include grid-media($media-md-only) {
    font-size: 1.7em; // 10px * 1.7em = 17px
  }
  @include grid-media($media-lg-only) {
    font-size: 1.8em; // 10px * 1.8em = 18px
  }
  @include grid-media($media-xl) {
    font-size: 1.9em; // 10px * 1.9em = 19px
  }
}

p {
  font-size: 1em;
  }

.special-case-element {
  font-size: 1.5rem; // 10px * 1.5 = 15px
}
```
In the above example, paragraph text is 16px in small devices, 17px in the medium breakpoint, 18 desktops, and 19 on widescreens, but `.special-case-element` will always be 15px, regardless of it's parent element. The ONLY exception being if the user sets their user-agent to a different unit, in which case, that element will be proportionally equivalent to 15px. By doing the legwork in the HTML and body elements, our entire typography stack will proportionally grow and shrink as appropriate. Additionally, if a user sets their user-agent to a different font size than the default, we know that our entire font stack will respond gracefully to it.

**Comment by sherakama** [comment]
Oh, where did it get set to 1em? That was a mistake if it happened. I bumped up the font size in the layouts example because I wanted to take up more screen space.

**Comment by kgcreative** [comment]
I think i caught it at a glance somewhere, but couldn't find it later. Either way, I wanted to get this thought process out, so it's now a half-formed blog post regarding responsive type systems.
