### ISSUE TITLE
Explore Font Awesome integration

### ISSUE THREAD

**Issue by sherakama** [SU-SWS/decanter#224]
Explore a way to include FA as a dependency

Also consider [FortAwesome](https://fortawesome.com/).

**Comment by buttonwillowsix** [comment]
https://fortawesome.com/

**Comment by buttonwillowsix** [comment]
Discuss before Decanterpalooza since icon block and link tickets depend on this.

**Comment by buttonwillowsix** [comment]
@kerri-augenstein remind us about any custom icon ideas you have. :)

**Comment by kerri-augenstein** [comment]
@buttonwillowsix we do have a growing set of custom icons already designed, plus the assumption of a subset of fontawesome (or all of fontawesome) or fortawesome (which also looks fine). what should we discuss prior to the sprint that would impact how we build?

**Comment by sherakama** [comment]
We can have our cake. 

We need a way to require 3rd party dependencies safely and a place to store our own assets. We have the latter and just need a strategy for the former.

**Comment by kerri-augenstein** [comment]
@sherakama is that a ticket that should be made for the sprint? the investigation for a "storing our own assets strategy"?

**Comment by sherakama** [comment]
We have the asset management now with the webpack build system. So this ticket is just for including 3rd party dependencies reliably without duplication.

**Comment by buttonwillowsix** [comment]
So you said something about documenting dependencies. So I am putting this note here to remind us to add Font Awesome and whatever you decide to the section we are writing up here: https://github.com/SU-SWS/decanter/wiki/Use-Decanter

**Comment by sherakama** [comment]
We're in a good place with this now.
