### ISSUE TITLE
Improve documentation on Standards & Conventions

### ISSUE THREAD

**Issue by sherakama** [SU-SWS/decanter#230]
Expand and add more details to: https://github.com/SU-SWS/decanter/wiki/Standards-and-Conventions

For: 
- Twig
- Mixins
- SCSS Variables
- Naming conventions
- BEM 
- File organization

**Comment by annawatt** [comment]
Joe working with Caryl & Cynthia on documentation for this?

**Comment by buttonwillowsix** [comment]
The page that now (maybe) needs updating is this one:
https://decanter.stanford.edu/page/about-contributing/
Do we have other things we need to update? Feels like (at a minimum) there are some naming conventions we don't have co covered?
