### ISSUE TITLE
Tweaks to existing Break Points; adding a 2XL break point

### ISSUE THREAD

**Issue by kerri-augenstein** [SU-SWS/decanter#234]
Based on what we would like to see for our menus shifting to hamburger and for adding in the margins we want on desktop, these adjusted breakpoints meet our design requirements to a degree more fine tuned than our previous set. 

Request for these breakpoints that mirror Bootstrap4
	•	XS=0
	•	SM=576
	•	MD=768
	•	LG=992
	•	XL=1200 
	•	NEW:2XL=1500

Additionally, we would like to add in this new 2XL = 1500px at the end. We would prefer not to document this break point in design files, but to deal with it in code, where by it's a simple calculation of the base font size in our 2XL modular scales (from 18px to 19px).

**Comment by sherakama** [comment]
This work is in #271
