### ISSUE TITLE
Vertical rhythm for elements

### ISSUE THREAD

**Issue by sherakama** [SU-SWS/decanter#247]
Create mixins and helpers to accomplish vertical rhythm.

**Comment by sherakama** [comment]
Grids branch has some rhythm.

- Grids
- Removed the top margin on headings and paragraphs
- Modular spacing

**Comment by sherakama** [comment]
@yvonnetangsu & @josephgknox this is the ticket for the vertical spacing with the grids.

**Comment by sherakama** [comment]
https://iamvdo.me/en/blog/css-font-metrics-line-height-and-vertical-align

Vertical rhythm primer for fonts.

**Comment by yvonnetangsu** [comment]
Thanks for sharing the link! Will read before meeting 👍

**Comment by buttonwillowsix** [comment]
Do a review and make sure that none of our components have any whitespace outside of the container, and decide what else needs to be done.

**Comment by sherakama** [comment]
Can we create a set of tools (mixins, functions, whatever) that can support creating vertical rhythm outside of the Decanter project?

**Comment by kerri-augenstein** [comment]
A few questions... 

1. Will Decanter components include "no container" and "container" displays? (impacting internal padding and the concept of "no space outside the container)

2. One way to accomplish spacing is by adding a "spacer" component that the user includes. Something we should think about adding into Decanter? Maybe there are two different sizes (aka heights)

**Comment by yvonnetangsu** [comment]
Seems like we've been doing this by project. Probably not doing in v6.
