### ISSUE TITLE
Update breakpoints with latest from designers

### ISSUE THREAD

**Issue by josephgknox** [SU-SWS/decanter#273]
See "Responsive Notes" at https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Stanford-Design-Library?node-id=2623%3A3861

**Comment by sherakama** [comment]
It would be good to bundle this in to the work at https://github.com/SU-SWS/decanter/pull/271

**Comment by sherakama** [comment]
Yes, please do.
