### ISSUE TITLE
Move images to www-media.stanford.edu

### ISSUE THREAD

**Issue by JBCSU** [SU-SWS/decanter#296]
Decanter's scss refers to a number of images, e.g `arrow-down.svg`, `external-link.svg`. Sites built on decanter end up with css that deep-links into `node-modules/decanter/...`. These url's that deep link into an npm packages do not work when deployed to a production site.

Let's host all of theses images (and any other assets referred to via url's) on www-media.stanford.edu. JB or Scott can upload the assets to the appropriate S3 bucket. Then we just need to update all the relative urls in our scss to point to those absolute url's.

**Comment by sherakama** [comment]
Look into the possibility of using webpack to package up assets and either embed with base64 encoding directly into the CSS or to create a 'package' with all the paths correct.

**Comment by sherakama** [comment]
Webpack does a great job at managing assets. Closing as I think we have a path forward.
