### ISSUE TITLE
Consolidate z-indexes into a single map / .scss file

### ISSUE THREAD

**Issue by JBCSU** [SU-SWS/decanter#305]
**Goal**
Be able to quickly determine the z-index stacking order of decanter components, e.g. skiplinks, nav.

**Describe alternatives you've considered**
For Stanford's homesite, Kevin had the following in `scss/layout/_layout.scss`:
```
// --------------------------------------------------------------------------------
// z-index
// --------------------------------------------------------------------------------
#splash--wordmark, #splash--scroller, #splash--pause {   z-index: 50;    }
#search-overlay, #menu-overlay                       {   z-index: 80;    }
#site-navigation                                     {   z-index: 80;    }
#site-search                                         {   z-index: 90;    }
body > header > section#alert, .widget_alert         {   z-index: 90;    }
#brand-bar                                           {   z-index: 100;   }
body > header > nav                                  {   z-index: 100;   }
#search-toggle, #menu-toggle {
                                                      z-index: 100;
  #{$hocus}                                       {   z-index: 110;   }
}
#site-navigation                                  {   z-index: 110;   }
#wpadminbar                                       {   z-index: 190;   }
#skiplinks                                        {   z-index: 200;   }
.widget_alert                                     {   z-index: 300;   }

// --------------------------------------------------------------------------------
// Flexbox visual order
// --------------------------------------------------------------------------------
#skiplinks                                        {   order: -51;     }
body > header                                     {   order: -50;     }
body > #main, body > main                         {   order: 1;       }
body > footer                                     {   order: 50;      }
```

This made it very easy to determine what was stacking on top of what, and what value we needed to set when we added new components.

Of course on homesite we knew precisely how to target each component on our site. We don't know this in Decanter.

**Proposed solution**
Perhaps we can move all `z-index` settings into a map set with default values and referred to by the relevant mixins.

**Comment by buttonwillowsix** [comment]
https://css-tricks.com/handling-z-index/

**Comment by buttonwillowsix** [comment]
This could also be done with a nice looking function: https://jonsuh.com/blog/organizing-z-index-with-sass/

**Comment by buttonwillowsix** [comment]
Putting existing z-indexes here for my reference:
`.su-hero__card
  z-index: 10;

.su-main-nav {
    z-index: 9999;

.su-main-nav__menu-lv2 {
  z-index: 11111; //When menu wrap to 2nd line make sure dropdown covers up top level links

@mixin skiplinks:focus
  z-index: 11222;

@mixin fancy-hover
  z-index: 1;

.su-cta__img
  z-index: 0;

.su-cta__button
  z-index: 100;


#kss-node > .su-brand-bar
      z-index: 11200;

.kss-guides-mode .kss-modifier__example,
.kss-guides-mode .kss-modifier__example-footer {
  &:before,
  &:after {
    z-index: -1;


// Main Nav Component - fix z-index in styleguide demo when multiple nav variants are right on top of each other.
    #kssref-components-main-navigation {
      .kss-modifier__example {
        @for $i from 2 through 8 {
          &:nth-child(#{3 * $i}) {
            nav {
              z-index: 9999 - 100 * ($i - 1);
            }


.masthead
  z-index: 20;

.kss-toolbar__tooltip {
    z-index: 1;

.kss-modifier__example {
    z-index: 0; // Establishes a local stacking context.

    &.kss-guides-mode .kss-modifier__example,
    &.kss-guides-mode .kss-modifier__example-footer {
      &:before,
      &:after {
        z-index: -1;



.kss-modifier__example {
          z-index: 11222;
        }


.kss-toolbar__tooltip {
  z-index: 1;

@mixin visible-grid {
  z-index: -100;`

**Comment by sherakama** [comment]
I'd say we are at won't do for version 6 and this won't be needed for version 7
