### ISSUE TITLE
Create aspect ratio container mixin

### ISSUE THREAD

**Issue by yvonnetangsu** [SU-SWS/decanter#310]
Stanford homepage's codebase:
https://code.stanford.edu/ucomm/homesite-2017/blob/master/wp-content/themes/homesite17/scss/utilities/mixins/_ar-container.scss

**Comment by buttonwillowsix** [comment]
@yvonnetangsu were you thinking about something like this? https://gist.github.com/jonathantneal/a9b8901273475d261dd3

**Comment by yvonnetangsu** [comment]
> @yvonnetangsu were you thinking about something like this? https://gist.github.com/jonathantneal/a9b8901273475d261dd3

Yes, something like that. There's a version of it in the Stanford homepage's codebase. I might be able to dig something out.

**Comment by sherakama** [comment]
This is done.
