### ISSUE TITLE
Accessibility Report: Alert Component

### ISSUE THREAD

**Issue by sherakama** [SU-SWS/decanter#313]
Use the AMP tool to scan the [Alert](http://decanter.stanford.edu/section-components.html#kssref-components-alert) component for accessibility issues and document them to this ticket.

**Comment by buttonwillowsix** [comment]
<img width="643" alt="Screen Shot 2019-03-14 at 1 59 13 PM" src="https://user-images.githubusercontent.com/205281/54387596-6d3d0b80-4661-11e9-803a-55dfbb3948e2.png">
I don't yet have testing access on AMP, but alerts passed using Google devtools
