### ISSUE TITLE
Accessibility Report: Button Component

### ISSUE THREAD

**Issue by sherakama** [SU-SWS/decanter#315]
Use the AMP tool to scan the [Button](http://decanter.stanford.edu/section-components.html#kssref-components-button) component for accessibility issues and document them to this ticket.

**Comment by buttonwillowsix** [comment]
Button also passes with 100%
<img width="715" alt="Screen Shot 2019-03-14 at 3 50 30 PM" src="https://user-images.githubusercontent.com/205281/54393914-0b849d80-4671-11e9-80b1-a41a1052db3f.png">
