### ISSUE TITLE
Accessibility Report: CTA Component

### ISSUE THREAD

**Issue by sherakama** [SU-SWS/decanter#317]
Use the AMP tool to scan the [CTA](http://decanter.stanford.edu/section-components.html#kssref-components-cta) component for accessibility issues and document them to this ticket.

**Comment by yvonnetangsu** [comment]
Assign to myself for now but anyone else feel free to take over if I don't get to this on time

**Comment by yvonnetangsu** [comment]
![Screen Shot 2019-03-14 at 1 30 09 PM](https://user-images.githubusercontent.com/42749717/54389746-141fa880-465e-11e9-834f-38556c59f7dc.png)
