### ISSUE TITLE
Accessibility Report: Main Navigation Component

### ISSUE THREAD

**Issue by sherakama** [SU-SWS/decanter#323]
Use the AMP tool to scan the [Main Navigation](http://decanter.stanford.edu/section-components.html#kssref-components-main-navigation) component for accessibility issues and document them to this ticket.

**Comment by yvonnetangsu** [comment]
Assign to myself

**Comment by yvonnetangsu** [comment]
![Screen Shot 2019-03-14 at 1 30 38 PM](https://user-images.githubusercontent.com/42749717/54389724-0702b980-465e-11e9-95d4-1f737647389e.png)
