### ISSUE TITLE
Accessibility Report: Quote Component

### ISSUE THREAD

**Issue by sherakama** [SU-SWS/decanter#324]
Use the AMP tool to scan the [Quote](http://decanter.stanford.edu/section-components.html#kssref-components-quote) component for accessibility issues and document them to this ticket.

**Comment by yvonnetangsu** [comment]
Assign to myself for now

**Comment by yvonnetangsu** [comment]
![Screen Shot 2019-03-14 at 1 31 30 PM](https://user-images.githubusercontent.com/42749717/54389699-f3575300-465d-11e9-8dcd-8c6f56ed8b75.png)
