### ISSUE TITLE
Accessibility Report: Search Component

### ISSUE THREAD

**Issue by sherakama** [SU-SWS/decanter#325]
Use the AMP tool to scan the [Search](http://decanter.stanford.edu/section-components.html#kssref-components-site-search) component for accessibility issues and document them to this ticket.

**Comment by yvonnetangsu** [comment]
I need to learn how to set up AMP so I'm assigning this to myself

**Comment by yvonnetangsu** [comment]
![Screen Shot 2019-03-14 at 1 33 49 PM](https://user-images.githubusercontent.com/42749717/54389659-da4ea200-465d-11e9-993a-dc877e259442.png)
100%
