### ISSUE TITLE
Create alternatives/variants for Hero component

### ISSUE THREAD

**Issue by josephgknox** [SU-SWS/decanter#336]

**Comment by buttonwillowsix** [comment]
2-3 more variants (Color, gradient) + Clean up video one (hiding and showing overlay).

- Split into two tickets. One for video (can look at Earth)
- Cap variants 2-3

**Comment by kerri-augenstein** [comment]
Designs created for variants on existing banner/hero treatment. Plus two additional design-treatments and variants for those. 

**Default hero (existing in code)** 
http://decanter.stanford.edu/section-components.html#kssref-components-hero
- Please rename to "Default Banner A Bottom Left" 

**New Variants: Banner A** 

Banner A Bottom Right 
https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Stanford-Design-Library?node-id=4494%3A7619
![banner-a-bottom-right](https://user-images.githubusercontent.com/26723613/59536149-f104cf00-8ec0-11e9-9890-fdca74946b2a.png)

Banner A Top Left
https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Stanford-Design-Library?node-id=4494%3A6416
![banner-a-top-left](https://user-images.githubusercontent.com/26723613/59536220-17c30580-8ec1-11e9-9301-e510466a0a27.png)

Banner A Top Right
https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Stanford-Design-Library?node-id=4494%3A7114
![banner-a-top-right](https://user-images.githubusercontent.com/26723613/59536253-2f9a8980-8ec1-11e9-9018-fcc898614292.png)

**Comment by kerri-augenstein** [comment]
Designs created for variants on existing banner/hero treatment. Plus two additional design-treatments and variants for those. 

### **1. Please rename "Hero" to "Banner"** 

### **2. Default hero (existing in code)** 
http://decanter.stanford.edu/section-components.html#kssref-components-hero
Please rename to "Default Banner A Bottom Left" 

### **3. New Variants: Banner A** 

Banner A Bottom Right 
[Figma documentation](https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Stanford-Design-Library?node-id=4494%3A7619)
![banner-a-bottom-right](https://user-images.githubusercontent.com/26723613/59536149-f104cf00-8ec0-11e9-9890-fdca74946b2a.png)

Banner A Top Left
[Figma documentation](https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Stanford-Design-Library?node-id=4494%3A6416)
![banner-a-top-left](https://user-images.githubusercontent.com/26723613/59536220-17c30580-8ec1-11e9-9301-e510466a0a27.png)

Banner A Top Right
[Figma documentation
](https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Stanford-Design-Library?node-id=4494%3A7114)
![banner-a-top-right](https://user-images.githubusercontent.com/26723613/59536253-2f9a8980-8ec1-11e9-9018-fcc898614292.png)


### **4. New Treatment : Banner B**

Banner B Centered 
[Figma documentation](https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Stanford-Design-Library?node-id=4299%3A466)
![banner-b-centered](https://user-images.githubusercontent.com/26723613/59536355-7daf8d00-8ec1-11e9-8c92-728305d38698.png)

Banner B Left
[Figma documentation](https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Stanford-Design-Library?node-id=4419%3A6791)
![banner-b-left](https://user-images.githubusercontent.com/26723613/59536555-fb739880-8ec1-11e9-9cbc-9020a29e644b.png)

### **5. New Treatment : Banner C**

Banner C Left
[Figma documenation](https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Stanford-Design-Library?node-id=4419%3A11091)
![banner-c-left](https://user-images.githubusercontent.com/26723613/59536610-25c55600-8ec2-11e9-968f-3228e8bee527.png)

Banner C Right
[Figma documentation](https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Stanford-Design-Library?node-id=4494%3A10029)
![banner-c-right](https://user-images.githubusercontent.com/26723613/59536672-41306100-8ec2-11e9-8a87-aa547b30cfe2.png)

**Comment by buttonwillowsix** [comment]
Prioritize Banner B Centered.
