### ISSUE TITLE
Create additional link components

### ISSUE THREAD

**Issue by josephgknox** [SU-SWS/decanter#341]
- External link
- Download link 
- Video link
- Jump link
- Internal link

Source: https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Stanford-Design-Library?node-id=76%3A4256

<img width="184" alt="additional_link_styles" src="https://user-images.githubusercontent.com/26723613/59152402-42b8df80-8a11-11e9-8875-e0ff53c147fe.png">

Icons are documented in Figma here: 
https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Stanford-Design-Library?node-id=2213%3A544

**Comment by sherakama** [comment]
Is this ticket a create more link components as additional components or is it a more link component as in read more?

**Comment by josephgknox** [comment]
Thanks for asking for clarification here. I can see how this can read in a few ways. Ha! This is to add additional link components. I will rename the ticket, using the word "additional" instead of "more."

**Comment by buttonwillowsix** [comment]
Have Kerri do design & Scope BEFORE decanterpalooza. Otherwise have Kerri spend time during decanterpalooza?

**Comment by buttonwillowsix** [comment]
- make a more generic icon + link (with a few choices?)
- look at states for all links? (more link, etc.)

**Comment by buttonwillowsix** [comment]
Dena to split into one ticket for looking at states and another ticket for looking at new link types.

**Comment by yvonnetangsu** [comment]
Done
