### ISSUE TITLE
Namespace all decanter variables

### ISSUE THREAD

**Issue by buttonwillowsix** [SU-SWS/decanter#382]

**Comment by buttonwillowsix** [comment]
To avoid conflicts with other variables.

**Comment by buttonwillowsix** [comment]
Adding @rebeccahongsf so she is aware of this ticket as she makes some new mixins.

**Comment by JBCSU** [comment]
Per discussion with @sherakama, we're limiting the scope of this to variables only.

I will investigate the pros and cons of simply adding an `su-` prefix to all variables vs. merging all our variables into one giant `decanter` map.

**Comment by yvonnetangsu** [comment]
Done!
