### ISSUE TITLE
Refactor main nav's default, light, and dark variants to use maps

### ISSUE THREAD

**Issue by JBCSU** [SU-SWS/decanter#386]
On the [new events calendar](events-dev.stanford.edu), Scott needs to override some of the colors in the nav, including hover states, expanded states, and collapsed states. That is currently very difficult because the nav's .scss uses deeply nested selectors that refer to colors directly from the color palette. He can't just change the value of, for example, `$color-black` before he includes `_main-nav--light.scss`, because that would change black everywhere. His only alternative currently is to copy and paste the light variant's entire scss and replace the color names.

I would like for the colors of the default nav, as well as the light and dark variants, to be specified in a scss map, similar to how theme colors are defined in homesite. That would allow someone to specify a custom map to get customized colors for their nav without having to either change a core color or completely replicate the scss in their project. It would probably also reduce the redundancy in Decanter's scss, as the same scss could be for all the variants - we just re-use it with different maps.

Note that currently we use different svg's to get different colors for the collapsed / expanded indicators. Hopefully the maps can include the path to the correct svg, so the colors of those controls can also be customized.

**Comment by sherakama** [comment]
I like where you are going with this idea and this definitely ties in with the global levers issue we have.

As a quick aside, you can color SVGs using this one neat css trick...
https://css-tricks.com/almanac/properties/f/fill/

**Comment by JBCSU** [comment]
That `fill` property is a neat trick to know to recolor foreground svg's. Sadly, it doesn't seem to work for the nav icons, presumably because they're background images. :( But thanks for the tip!

**Comment by yvonnetangsu** [comment]
It might be worth it for us to do more research into how best to use svg icons. Perhaps use image instead as content CSS property, or image-mask (which allows you to change the color of the icon with the change of background-color).

**Comment by sherakama** [comment]
https://css-tricks.com/change-color-of-svg-on-hover/

**Comment by yvonnetangsu** [comment]
@sherakama, yeah, the mask option seems pretty promising. I also looked at the filter one initially, but it doesn't seem to work on IE (maybe even Edge) - that calculator for target color is handy though!

**Comment by yvonnetangsu** [comment]
Done
