### ISSUE TITLE
Accessibility for Link: Ensure keyboard focus is indicated visually 

### ISSUE THREAD

**Issue by cjwest** [SU-SWS/decanter#401]
**Describe the bug**
***Ensure keyboard focus is indicated visually (Severity: 7)***
The last three links, with styles .su-button, .su-button--secondary, and .su-button--big do not have a visible indication of focus in high contrast mode.  [User Impact] Users with low vision who enable high contrast mode will not be able to track their location on the page and tell when these links have focus.  
[Code Reference]
```
<a href="https://decanter.stanford.edu/" class="su-link su-button">Example Link Text</a>

<a href="https://decanter.stanford.edu/" class="su-link su-button--secondary">Example Link Text</a>

<a href="https://decanter.stanford.edu/" class="su-link su-button--big">Example Link Text</a>
```

**To Reproduce**
1. http://decanter.stanford.edu/section-components.html#kssref-components-lockup

**Expected behavior**
Provide a highly visible indication of focus that persists in high contrast mode. This can be done with CSS outline styles.

**Screenshots**
![image](https://user-images.githubusercontent.com/284440/56447777-2f19b400-62bf-11e9-9a4a-2278ff42e17b.png)

**Additional context**
https://stanford.levelaccess.net/public/reporting/view_module.php?module_id=9631558

**Comment by yvonnetangsu** [comment]
Outlines have been added back to all Decanter buttons
