### ISSUE TITLE
Accessibility for global footer: Avoid inappropriate use of ARIA roles, states, and properties 

### ISSUE THREAD

**Issue by cjwest** [SU-SWS/decanter#405]
**Accessibility for global footer**
***Avoid inappropriate use of ARIA roles, states, and properties (Severity: 5)***
The `<nav>` element is given a redundant `role="navigation"`, which is not necessary.  
[User Impact] 
The practical impact is likely to be slim to none, but the addition of the role adds no value as it has the same semantics as the native `<nav>` element.  
[Code Reference] 
`<nav role="navigation">`

**To Reproduce**
1. http://decanter.stanford.edu/section-components.html#kssref-components-global-fo
oter

**Expected behavior**
[Expected Behavior]
Remove the redundant `role="navigation"`.

[Code Example]
`<nav>`

**Screenshots**

![image](https://user-images.githubusercontent.com/284440/56448194-2a0a3400-62c2-11e9-93da-0a5d8760e6e0.png)

**Additional context**
https://stanford.levelaccess.net/public/reporting/view_module.php?module_id=9631560

**Comment by yvonnetangsu** [comment]
role="navigation" has been removed in global footer nav
