### ISSUE TITLE
Accessibility for Card: Ensure heading level matches the heading's visual importance/level

### ISSUE THREAD

**Issue by cjwest** [SU-SWS/decanter#407]
**Accessibility for Card**
***Ensure heading level matches the heading's visual importance/level (Severity: 3)***

The headings are out of logical order, with h4 going before h3. Though the visual weight may match the heading level, the structure being communicated by these levels may not be clear.

[User Impact]
Screen reader users may not understand the relationships of content and be able to tell how these headings related to one another when they appear to be out of order.

[Code Reference]
```
<h4>This is a super headline</h4>
<h3>Headline goes here</h3>
```

**To Reproduce**
1. http://decanter.stanford.edu/section-components.html#kssref-components-card

**Expected behavior**
[Expected Behavior]
Ensure the heading order accurately communicates the content structure. This would likely be more easily understood with the heading order reversed or with the actual headings themselves being reversed.

[Code Example]
```
<h3>This is a super headline</h3>
<h4>Headline goes here</h4>

or

<h3>Headline goes here</h3>
<h4>This is a super headline</h4>
```

**Screenshots**

![image](https://user-images.githubusercontent.com/284440/56448378-6ab67d00-62c3-11e9-84ff-fc5080c9f27e.png)

**Additional context**
https://stanford.levelaccess.net/public/reporting/view_module.php?module_id=9631562

**Comment by yvonnetangsu** [comment]
Addressing this by changing h4 to a span for the superheadline in #444

**Comment by yvonnetangsu** [comment]
Also changed headline from h3 to h2
