### ISSUE TITLE
Accessibility for Embed: Ensure headings and labels are descriptive and unique 

### ISSUE THREAD

**Issue by cjwest** [SU-SWS/decanter#410]
**Accessibility for Embed**
***Ensure headings and labels are descriptive and unique (Severity: 3)***

The "Close" buttons for both the Share dialog and the suggested videos only say "close" which is not descriptive.

[User Impact]
Screen reader users may not be able to tell what they will be closing.

[Code Reference]
Suggested videos close button:
```
<button class="ytp-button ytp-collapse" aria-label="Close"><svg height="100%" viewBox="0 0 16 16" width="100%"><path d="M13 4L12 3 8 7 4 3 3 4 7 8 3 12 4 13 8 9 12 13 13 12 9 8z" fill="#fff"></path></svg></button>
```
Share dialog close button:
```
<button class="ytp-share-panel-close ytp-button" aria-label="Close" title="Close"><svg height="100%" viewBox="0 0 24 24" width="100%"><path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z" fill="#fff"></path></svg></button>
```

**To Reproduce**
1. http://decanter.stanford.edu/section-elements.html#kssref-elements-embedcontainer

**Expected behavior**
Add more descriptive text to the button labels so users know what they are closing.

[Code Example]
```
<button class="ytp-button ytp-collapse" aria-label="Close Suggested Videos"><svg height="100%" viewBox="0 0 16 16" width="100%"><path d="M13 4L12 3 8 7 4 3 3 4 7 8 3 12 4 13 8 9 12 13 13 12 9 8z" fill="#fff"></path></svg></button>
```
Share dialog close button:
```
<button class="ytp-share-panel-close ytp-button" aria-label="Close Share Dialog" title="Close"><svg height="100%" viewBox="0 0 24 24" width="100%"><path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z" fill="#fff"></path></svg></button>
```
**Screenshots**

![image](https://user-images.githubusercontent.com/284440/56448669-0e089180-62c6-11e9-883b-cbcaace274fb.png)

**Additional context**
https://stanford.levelaccess.net/public/reporting/view_instance.php?instance_id=1058182584

**Comment by sherakama** [comment]
Not much we can do about Youtube's player.
