### ISSUE TITLE
CSS grid gaps are not being rendered in Edge

### ISSUE THREAD

**Issue by yvonnetangsu** [SU-SWS/decanter#412]
**Describe the bug**
Decanter CSS grid gaps are not showing up when viewed with Microsoft Edge. Grid gaps on other websites do show up.

**To Reproduce**
1. Use Edge or Browserstack
2. Look at any of the CSS grid layout or the horizontal card component
3. See if the grid gaps are being rendered

**Expected behavior**
There should be grid gaps

**Desktop (please complete the following information):**
 - Windows 10
 - Edge (18, 17, 16)

**Comment by sherakama** [comment]
Fixed
