### ISSUE TITLE
SR only text helper causes overflow

### ISSUE THREAD

**Issue by yvonnetangsu** [SU-SWS/decanter#414]
**Describe the bug**
When used on some sites, the .su-sr-only-text helper causes overflowing and takes up height (shows empty space).

**Expected behavior**
The .su-sr-only-text shouldn't take up any space and should only be invisible and not change the page's appearance in any way.

**Screenshots**

![Screen Shot 2019-05-01 at 2 58 41 PM](https://user-images.githubusercontent.com/42749717/57045231-c406a080-6c21-11e9-8acd-2e4b6b4e423d.png)

The blue focus ring shows the empty space caused by the .su-sr-only-text (skip link h2) and also the .su-sr-only-text after "Read me" is still showing and overflowing.

**Comment by kgcreative** [comment]
I seem to recall there being a .sr-only-text which is good for in-line elements, vs either .sr-only-element, or .hide-visually (I forget which one), which hides block-level elements.

**Comment by yvonnetangsu** [comment]
> I seem to recall there being a .sr-only-text which is good for in-line elements, vs either .sr-only-element, or .hide-visually (I forget which one), which hides block-level elements.

Yup, just opened a PR to use .hide-visually instead 👍

**Comment by kgcreative** [comment]
Good detective work! 😎 also, hi Yvonne! 👋

**Comment by yvonnetangsu** [comment]
Great seeing you here, @kgcreative ! 😄
