### ISSUE TITLE
Investigate the best way to include custom icons into our system

### ISSUE THREAD

**Issue by kerri-augenstein** [SU-SWS/decanter#423]
Look at various ways to enable using icons. 

**Requirements**
- Easy to change the color of the icon using css 
- Use custom icons created by designers in Figma

**Comment by yvonnetangsu** [comment]
We're going with the `mask` method so we can change the svg icon colors using `background-color` in css. However, IE doesn't understand `mask`, so we'll be hiding the icons in IE since they are not absolutely necessary.
