### ISSUE TITLE
Big Numbered List

### ISSUE THREAD

**Issue by buttonwillowsix** [SU-SWS/decanter#433]
Another variant on a list, to be used in a WYSIWYG to style an ordered list.

Example: https://undergrad.stanford.edu/photo-contest.

For more context about this issue: 

https://docs.google.com/document/d/1BVBr71fxqSEzxP-yb3MAQ_5Dm2i9bY9KydJZfV_Aaxk/edit#

**Comment by yvonnetangsu** [comment]
dibs
