### ISSUE TITLE
Card variant for “non-card” style - no background container (vertical + horizontal)

### ISSUE THREAD

**Issue by buttonwillowsix** [SU-SWS/decanter#437]
remove border
remove background color
remove shadow 

For more context: 
https://docs.google.com/document/d/1BVBr71fxqSEzxP-yb3MAQ_5Dm2i9bY9KydJZfV_Aaxk/edit#

**Comment by yvonnetangsu** [comment]
Are we calling this variant .su-card--fake? 😄

**Comment by kerri-augenstein** [comment]
@JBCSU think we should screenshare after our standup to review, as I'm not setup to see the changes.
