### ISSUE TITLE
Adjust the Modular Scale multiplier for Display A and B at XS and SM

### ISSUE THREAD

**Issue by kerri-augenstein** [SU-SWS/decanter#471]
Add a 0.8 multiplier for @display-a and @display-b at XS and SM breakpoints so they look more proportional at these small screen resolutions.

**Comment by yvonnetangsu** [comment]
Adding my Google Sheet with an idea for the approach - 
https://docs.google.com/spreadsheets/d/1A5jYD-7Z86GzvZ-6ld7D2SJDHpJjJYVDoMlTZx732JY/edit?usp=sharing
