### ISSUE TITLE
Fix glyphs in links so it doesn't render weird characters

### ISSUE THREAD

**Issue by yvonnetangsu** [SU-SWS/decanter#484]
**Describe the bug**
Sometimes for example a .su-link--more would render weird characters - 
![Screen Shot 2019-08-21 at 5 01 34 PM](https://user-images.githubusercontent.com/42749717/63556310-29480f80-c4f9-11e9-9fbc-a165dba6ddab.png)

**To Reproduce**
1. We see this when we use the mixin `@include link-glyph('\00BB');` on our WordPress template Redwood. This doesn't happen consistently but does happen.

**Expected behavior**
It should just render the double chevrons.

**Comment by sherakama** [comment]
🤔 Where does this show up? In the rendered output of the styleguide?

**Comment by yvonnetangsu** [comment]
> 🤔 Where does this show up? In the rendered output of the styleguide?

It's the weirdest thing. Happens on our WordPress template sometimes when we use the mixin `@include link-glyph('\00BB');` I'm beginning to think it might be something in our WP template and not a Decanter issue but I'm not sure.

**Comment by sherakama** [comment]
From my experience, these things are typically caused by wrong character encoding and invisible gremlins. Ensure your WP template and all contents are UTF-8.

**Comment by yvonnetangsu** [comment]
> From my experience, these things are typically caused by wrong character encoding and invisible gremlins. Ensure your WP template and all contents are UTF-8.

Yeah, I'm going to double check all of our contents are UTF-8. It does seem like all the SCSS files and rendered HTML are UTF-8, but I agree that something is missing somewhere.

**Comment by yvonnetangsu** [comment]
Apparently this isn't an issue that's only happening for our WordPress theme. It shows up on the styleguide also 🤔 

In our WP theme, instead of using the `@link-glyph` mixin, we added `content: '\00BB'; `directly and that fixes the problem. 

Since there are only 2 link variants that use `@link-glyph`, maybe we can just get rid of the mixin and add the `content` part directly to the selector.

![Screen Shot 2019-10-03 at 10 11 57 AM](https://user-images.githubusercontent.com/42749717/66148801-92c24000-e5c6-11e9-956d-fb76694bc30c.png)

**Comment by sherakama** [comment]
That sounds to me like you have tracked down the culprit.

I wasn't able to reproduce the strange characters but you may want to try and remove the quotes around the interpolated $glyph variable on line 17 of _link_glyph.scss.

eg:
From `content: '#{$glyph}';` to `content: #{$glyph};`

**Comment by yvonnetangsu** [comment]
> That sounds to me like you have tracked down the culprit.
> 
> I wasn't able to reproduce the strange characters but you may want to try and remove the quotes around the interpolated $glyph variable on line 17 of _link_glyph.scss.
> 
> eg:
> From `content: '#{$glyph}';` to `content: #{$glyph};`
> 
> or remove the interpolation altogether if it is not needed.

Yeah, it doesn't happen consistently. And good idea, I'll try fiddling with the quotes etc and see if that change things.

**Comment by sherakama** [comment]
After a quick test, I don't think the interpolation is needed as the parameter is passed in as a string.

**Comment by yvonnetangsu** [comment]
> After a quick test, I don't think the interpolation is needed as the parameter is passed in as a string.

Thanks for testing. I'll absorb that into my @link-icon vertical position PR.
