### ISSUE TITLE
How to use Figma with Decanter

### ISSUE THREAD

**Issue by buttonwillowsix** [SU-SWS/decanter#486]
Maybe videos!

**Comment by buttonwillowsix** [comment]
At a minimum: link to download Figma, instructions on how to get/request access to Decanter Figma libraries

**Comment by buttonwillowsix** [comment]
@kerri-augenstein are you just going to put this info on the "As a Designer" page?

**Comment by kerri-augenstein** [comment]
@buttonwillowsix yea, let's kill this page for now, no content for it yet :)

**Comment by buttonwillowsix** [comment]
Closing. We can reopen if needed later.

**Comment by sherakama** [comment]
For future us to consider: https://www.figma.com/blog/introducing-figma-to-react/
