### ISSUE TITLE
Shadow error

### ISSUE THREAD

**Issue by koppieesq** [SU-SWS/decanter#49]
Whenever I compile sass, I get this error:

> WARNING: Material shadow supports a range from 1-12, or the keywords "flat, shallow, medium deep"
> Backtrace:
>         node_modules/decanter/core/utilities/functions/_material-shadow.scss:47, in function `material-shadow`
>         node_modules/decanter/core/utilities/mixins/_material-shadow.scss:28, in mixin `material-shadow`
>         node_modules/decanter/core/components/cards/_card.scss:43, in mixin `card`
>         patterns/molecules/simple-card/scss/simple-card.component.scss:13
> 
> WARNING: Material shadow supports a range from 1-12, or the keywords "flat, shallow, medium deep"
> Backtrace:
>         node_modules/decanter/core/utilities/functions/_material-shadow.scss:47, in function `material-shadow`
>         node_modules/decanter/core/utilities/mixins/_material-shadow.scss:28, in mixin `material-shadow`
>         node_modules/decanter/core/components/cards/_card.scss:43, in mixin `card`
>         patterns/molecules/simple-card/scss/simple-card.theme.scss:13

The offending code is located in this mixin: stanford_components/node_modules/decanter/core/components/cards/_card.scss line 8: `$material-shadow: null,`

I don't think material-shadow likes `null`

I don't actually need to do anything with shadows or simple-card, I just experienced this non-fatal error when I compiled.  Not sure if I should submit a patch?

**Comment by sherakama** [comment]
Thanks for posting this @koppieesq 

It looks like we had an older call to the material shadow function that had an incorrect parameter value. I have fixed it for you here: https://github.com/SU-SWS/stanford_components/pull/1/files#diff-15eb5c2e3841a1f2b73ff26f6c358d11R13

Thanks for posting this!

**Comment by sherakama** [comment]
You should already have that fix in your PR. Just pull down the latest.

Leave this open for now. I want to track down when/where this change was implemented to see if we broke the API at some point incorrectly. 

Thanks again.
