### ISSUE TITLE
Local Footer

### ISSUE THREAD

**Issue by kerri-augenstein** [SU-SWS/decanter#491]
Complete Decanter design documentation for local footer 
https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Stanford-Design-Library?node-id=5268%3A11637

**Comment by kerri-augenstein** [comment]
Design documentation complete. Ready for theming into Decanter or CMS.

**Comment by kerri-augenstein** [comment]
@sherakama should this live in Decanter or each CMS?

**Comment by sherakama** [comment]
This seems like a good Decanter type thing.

**Comment by yvonnetangsu** [comment]
Done .su-local-footer
