### ISSUE TITLE
Add in between spacers + larger spacer (3.5, 4.5, 6)

### ISSUE THREAD

**Issue by kerri-augenstein** [SU-SWS/decanter#492]
Size of spacers between 3 and 4 are too big, need to change these spacers, and add additional spacers — 6, 7, and 8 —to account for wider range of spacing needs. 

*Modular Scale 4*
3XL: Base *3.2

*Modular Scale 5*
4XL: Base 4

*Modular Scale 6*
5XL: Base 5

*Modular Scale 7*
6XL: Base 6

*Modular Scale 8*
7XL: Base 7

*Modular Scale 9*
8XL: Base 9

<img width="891" alt="Screen Shot 2019-09-18 at 3 54 23 PM" src="https://user-images.githubusercontent.com/26723613/65181272-abf6b880-da2c-11e9-90af-c55dd5ac418b.png">

**Comment by kerri-augenstein** [comment]
Ready for frontend dev

**Comment by yvonnetangsu** [comment]
I've decided to leave out the above part "getting rid of the media queries for modular-spacing at the lower end" since we rarely use the mixin at these lower end values anyway.

**Comment by sherakama** [comment]
Ok, great thanks Yvonne.
