### ISSUE TITLE
Add default card style

### ISSUE THREAD

**Issue by kerri-augenstein** [SU-SWS/decanter#495]
**Create a default card variable with these attributes:** 

background-color: $color-white

box-shadow: shallow (not sure what the variable is named)

border: gray-2 (not sure what the variable is named, this color is getting added in a different ticket) 

**Design mock:** 
<img width="465" alt="Screen Shot 2019-09-13 at 5 16 12 PM" src="https://user-images.githubusercontent.com/26723613/64895334-3b295800-d64a-11e9-8013-37ca20395d72.png">

**Comment by kerri-augenstein** [comment]
@yvonnetangsu I can't remember, is this a duplicate task?

**Comment by yvonnetangsu** [comment]
> @yvonnetangsu I can't remember, is this a duplicate task?

Actually, I'm not sure myself, @kerri-augenstein. It's possible that we could use this "empty" card style as a placeholder (in sass lingo, that's a block of reusable code).

**Comment by kerri-augenstein** [comment]
@yvonnetangsu works for me! Does that already exist?

**Comment by yvonnetangsu** [comment]
Closing this one since we aren't going to do more placeholders. I'll incorporate the style into the card CSS tweaks.
