### ISSUE TITLE
Repurpose "Splash Font" 

### ISSUE THREAD

**Issue by yvonnetangsu** [SU-SWS/decanter#501]
**Is your feature request related to a problem? Please describe.**
Currently splash font .su-splash-font is the same as h1/Type A. @kerri-augenstein and I would like to repurpose this into a display style that's even larger than the h1.

Splash font takes on @modular-typography(5), at xs and sm breakpoints, it has font size $su-displays-mobile-factor 0.85 x @modular-typography(5).

**Comment by sherakama** [comment]
Completed in #498
