### ISSUE TITLE
Tweak Section 3.9 - Links

### ISSUE THREAD

**Issue by kerri-augenstein** [SU-SWS/decanter#505]
Let's make some slight tweaks to these link and button styles. There are some animations ideas in here that might not be viable. Let's discuss. 

**.su-link-action**
```
.su-link--action::after {
  margin-bottom: 0; 
  height: 0.6em;
  width: 0.6em;
}
```
desired: 
<img width="99" alt="su-link--action" src="https://user-images.githubusercontent.com/26723613/66076135-247c6f80-e52b-11e9-885a-af82ac9c5d47.png">

**.su-link--download**
Can the download icon move down instead of left for the animation on this link?

**.su-link--external**
Can the icon move diagonally up and to the right instead of in a straight line to the right? 

**.su-link--interal**
I wonder if we could make an animation transition to an icon that was a filled in lock for the hover, instead of the outline, and not need to make it move right. 

**.su-link--jump**
Can the icon move down instead of to the right? 

**.su-link--video**
For the animation, I'm not sure. Do you have any ideas? We could make it expand in scale slightly, but that is very different from all of the other animations (same comment goes for the lock actually). Maybe these two should both fill-in on hover, and not move? Would love your thoughts here.
```
.su-link--video::after {
  margin-bottom: -5em;
  height: 0.9em;
  width: 0.9em;
}
```
Desired: 
<img width="108" alt="su-link--video" src="https://user-images.githubusercontent.com/26723613/66076152-2ba37d80-e52b-11e9-9213-e49c3aa97f72.png">

**Buttons** 
Add paper drop shadow to .su-button and .su-button--big

**Comment by yvonnetangsu** [comment]
@kerri-augenstein , the animation sounds good! How does the video one animate?

As for the button, how about I create a variant .su-button--shadow that has the paper shadow? Then the variant/class could be used in combination with any existing and future button variants to add paper shadow to those buttons.

**Comment by kerri-augenstein** [comment]
@yvonnetangsu Oh good catch! I edited the description above to include my comment there. But would love your ideas on that one and the lock icon as well.

**Comment by yvonnetangsu** [comment]
> @yvonnetangsu Oh good catch! I edited the description above to include my comment there. But would love your ideas on that one and the lock icon as well.

Hey @kerri-augenstein, hmmm...how about we go with moving to the right for the video one since the play button triangle kind of points to the right? Let me see how the lock one work out - I'll start working on this soon.

**Comment by kerri-augenstein** [comment]
@yvonnetangsu sounds great!

**Comment by yvonnetangsu** [comment]
Done.
