### ISSUE TITLE
Create Strawman IA

### ISSUE THREAD

**Issue by buttonwillowsix** [SU-SWS/decanter#539]
Create strawman IA, review, and prioritize elements

**Comment by buttonwillowsix** [comment]
Ingredients: https://docs.google.com/spreadsheets/d/1pGVTPv8no593C-xttjL3iuj6jhyRt5m6mlwcHvgUle4/edit#gid=0

**Comment by buttonwillowsix** [comment]
https://www.gloomaps.com/gjcQzYY2eh

**Comment by buttonwillowsix** [comment]
![gloomap_983229a2](https://user-images.githubusercontent.com/205281/69286867-384a6680-0ba9-11ea-9e7c-6963d1d4640c.png)

**Comment by buttonwillowsix** [comment]
^ @sherakama this version doesn't have ALL the things because GlooMaps seemed to have some issues with us both editing at the same time, but I think it will give you the idea of what we were thinking.

**Comment by sherakama** [comment]
So much thanks.
