### ISSUE TITLE
Re-theme sassdocs

### ISSUE THREAD

**Issue by buttonwillowsix** [SU-SWS/decanter#558]
-Re-theme lightly (or more)
-Reformat comments
-Add examples and parameter documentation as needed, if time

**Comment by cjwest** [comment]
The theme is here:
https://github.com/SU-SWS/sassdoc-theme-decanter

**Comment by buttonwillowsix** [comment]
Hold until D8 release

**Comment by buttonwillowsix** [comment]
Holding until after the D8 release

**Comment by sherakama** [comment]
Won't do.
