### ISSUE TITLE
Reformat sassdocs comments

### ISSUE THREAD

**Issue by buttonwillowsix** [SU-SWS/decanter#559]
-Add examples and parameter documentation as needed, if time

**Comment by buttonwillowsix** [comment]
I think if we merge in https://github.com/SU-SWS/decanter/pull/592 and https://github.com/SU-SWS/decanter/pull/595, we are gtg here.

**Comment by sherakama** [comment]
Yall are rockstars. This is done.

**Comment by sherakama** [comment]
won't do.
