### ISSUE TITLE
Page Review: About the Main Nav Component

### ISSUE THREAD

**Issue by buttonwillowsix** [SU-SWS/decanter#563]
Please review to make sure this represents the current state/future plans.

https://elegant-poitras-87214a.netlify.com/page/about-the-main-nav-component/

**Comment by buttonwillowsix** [comment]
@kerri-augenstein will merge this into the accessibility page.

**Comment by buttonwillowsix** [comment]
I merged this into the Accessibility page and now  it just needs to be reviewed/editing to reflect current practice/plans and to fit into the page.  Passing to Kerri/Yvonne

**Comment by sherakama** [comment]
Done.
