### ISSUE TITLE
Page Edit/Review: About

### ISSUE THREAD

**Issue by buttonwillowsix** [SU-SWS/decanter#573]
https://elegant-poitras-87214a.netlify.com/page/about/

Review text and consider link to governance and other related pages.

**Comment by buttonwillowsix** [comment]
Maybe this is really the home page?

**Comment by kerri-augenstein** [comment]
@buttonwillowsix I like having both, because people naturally look for About, even if it's mostly duplicative content.

**Comment by kerri-augenstein** [comment]
@sherakama your thoughts here?

**Comment by sherakama** [comment]
I like it. Doesn't need anything more than that. The navigation is clear (to me) that there is more to drill down into if the end-user is looking for something specific.

**Comment by kerri-augenstein** [comment]
@yvonnetangsu your thoughts here please and thanks!!

**Comment by yvonnetangsu** [comment]
@kerri-augenstein Looks good to me!

**Comment by kerri-augenstein** [comment]
@sherakama @yvonnetangsu  please double check this page for the new section on "open source". Is this the right language? Is this also where we talk about being able to download the framework and use it in the way you were mentioning yesterday?

**Comment by yvonnetangsu** [comment]
@kerri-augenstein True that it is open source, but we do have terms of use here which restricts usage to Stanford only - 
https://github.com/SU-SWS/decanter/blob/master/TERMSOFUSE.txt

**Comment by buttonwillowsix** [comment]
@kerri-augenstein, @yvonnetangsu, @sherakama  I think the download, etc. stuff is going on the Getting Started pages. 
Do we want to say, "however, please see our terms of use." in that open source section? Wouldn't it be true that just the brand elements are restricted?

**Comment by yvonnetangsu** [comment]
@buttonwillowsix , you know, I'm curious myself. If someone from outside wants to use our nav, for example, is that allowed? It doesn't have our logo on it. It seems like a grey area to me.

**Comment by sherakama** [comment]
Oh, we need to update that terms of use document to reflect the requirement of being aligned with the branding guidelines instead of the use of the project.

**Comment by sherakama** [comment]
Good enough for now.
