### ISSUE TITLE
Final review of pages

### ISSUE THREAD

**Issue by buttonwillowsix** [SU-SWS/decanter#576]
This is a ticket to track final review of pages before sending on to David/Rachel

**Comment by buttonwillowsix** [comment]
- All comments from David and Rachel have been integrated. Some feedback from Dana has also been added in.
- Issue tracking information has been removed and work-in-progress notes made where needed. 
- Links have been hooked up where needed
- Headers have been given a consistency pass
- Use of the term "Decanter" have been vetted for consistency

I think all in all, one more quick pass is needed for launch. Post launch, I think we can take a look at some of the overlapping/duplicate content we might have, and see if there are any gaps (maybe an outside developer review would be nice to have for identifying what they would expect to see here.)

**Comment by sherakama** [comment]
Good enough for now.
