### ISSUE TITLE
Figure out what to do with Roadmap and Release Notes

### ISSUE THREAD

**Issue by buttonwillowsix** [SU-SWS/decanter#577]
Would be nice if we could have release notes automagically plop in here? Or we can link.

For the roadmap, I have been looking with Rachel Manongdo at tools for displaying project roadmaps for D8, so maybe some overlap here.

**Comment by sherakama** [comment]
Roadmaps are hard to automagic but perhaps we could add an integration with github and link out to an active project board.

Releases are a bit easier but will need a quick chat about finessing the release notes are not for the general public.

**Comment by buttonwillowsix** [comment]
I see you added some release notes! Weeeee!
Doing roadmap example now... Rachel M. and I have been looking at Roadmap tools.

**Comment by buttonwillowsix** [comment]
Was thinking we could highlight the major stuff in a tool like this example (maybe not this tool, and definitely not this exact list, but you get the idea)

![Roadmap-Company-wide roadmap](https://user-images.githubusercontent.com/205281/70827718-08a50d80-1da7-11ea-8f00-e7dab5312c15.png)

And then link everything else to the projects page on Github.

**Comment by yvonnetangsu** [comment]
@buttonwillowsix I pulled those release notes from our changelogs - let me know if it's appropriate.

**Comment by buttonwillowsix** [comment]
Also, embeddable one:

<iframe src="https://decanter.aha.io/shared/ef0a93f323502e029c954cdc8226527b?header=false&footer=true"></iframe>

**Comment by buttonwillowsix** [comment]
Do we feel like we want to clean up release notes before putting them live?

**Comment by sherakama** [comment]
This project is primarily targeted at designers/developers so I am ok with the release notes going out 'as-is'

**Comment by yvonnetangsu** [comment]
@buttonwillowsix I copy and pasta-ed the latest release notes. Please feel free to review (or if you find a way to embed it please feel free to do so). Thanks!
https://elegant-poitras-87214a.netlify.com/admin/index.html#/workflow

**Comment by sherakama** [comment]
Looks good to me. Marked as 'ready'

**Comment by yvonnetangsu** [comment]
@sherakama I just published it :)
