### ISSUE TITLE
Page Content: Responsive Design & Layout

### ISSUE THREAD

**Issue by buttonwillowsix** [SU-SWS/decanter#579]
Maybe ditch these for launch if need be

**Comment by kerri-augenstein** [comment]
@buttonwillowsix I wonder if the section called "Layouts" becomes a single page for now? With some text describing the things? Not sure if we have the content here yet? (Or maybe we do from the existing site, but it would need to be added to yes, with text describing what the things were, how to use them, etc.

**Comment by sherakama** [comment]
I would like the Layouts section to be muli-tiered. I want to move all the layouts from the components section that we have with KSS now, to the layouts section. We also need to do a much better job at describing the showing examples of the flexbox and css grid systems that we have.

eg: https://getbootstrap.com/docs/4.0/layout/grid/

**Comment by buttonwillowsix** [comment]
@sherakama and @kerri-augenstein : so I can get a handle on what we want here. Is this still what we want?

<img width="177" alt="Screen Shot 2019-12-12 at 3 12 29 PM" src="https://user-images.githubusercontent.com/205281/70753415-f0bf8200-1cf1-11ea-80eb-cf18ea04630a.png">

**Comment by kerri-augenstein** [comment]
@buttonwillowsix this looks good to me!

**Comment by buttonwillowsix** [comment]
@rebeccahongsf, please see Shea's example above ^^^

**Comment by buttonwillowsix** [comment]
For the exact page on this ticket, I am going to put a "Coming soon" on the page.
