### ISSUE TITLE
Document decorator approach

### ISSUE THREAD

**Issue by buttonwillowsix** [SU-SWS/decanter#583]
Figure out where this goes in the sitemap and document what it means.

**Comment by sherakama** [comment]
Code standards and Components sections should have information on this.

**Comment by sherakama** [comment]
Decorators are CSS classes that are additive to a component and can combine to completely change the state, behavior, or aesthetics of a component. This is different from variants as they are an immutable composition.

**Comment by sherakama** [comment]
We can piggyback on tailwind's documentation for version 7.
