### ISSUE TITLE
Accessibility documentation to share

### ISSUE THREAD

**Issue by kerri-augenstein** [SU-SWS/decanter#587]
Need to add accessibility documentation that makes sense here, to share out to the University from our Decanter website. 

This link exists on the "Why Decanter" page. 
https://elegant-poitras-87214a.netlify.com/page/about-why-decanter/

Would like to post some examples of documents that might be relevant to the "public" to share, so that we demonstrate the massive effort we have undergone to support meeting accessibility requirements.

**Comment by kerri-augenstein** [comment]
@cjwest whenever you have time to look at this, let me know if you have any questions. There is a sibling UX Documentation folder in the same shared drive 
https://drive.google.com/drive/folders/15Jr7zIWphRb92VAP2_gOenZDY2HJ_HiQ

**Comment by cjwest** [comment]
@kerri-augenstein,
It would be helpful for me to talk through this with you.

**Comment by kerri-augenstein** [comment]
@cjwest no problem, let's do so after standup tomorrow!

**Comment by kerri-augenstein** [comment]
Team decided it was unnecessary at this time to keep a Drive folder for Accessibility documentation. We will link to the soap website for now.
