### ISSUE TITLE
Page Content: Brand

### ISSUE THREAD

**Issue by kerri-augenstein** [SU-SWS/decanter#594]
Could  we place the components for the 

- brand bar 
- local header 
- local footer 
- global footer

 

on this page

**Comment by yvonnetangsu** [comment]
@kerri-augenstein I know @sherakama is planning on having 3 pages under "Components" - "Simple", "Composite" and "Brand". Perhaps it is better to have the "Components -> Brand" page be the "Brand" page under "Brand + Design elements" instead? That way we don't have duplicate content. Under Components, we could just have "Simple" and "Composite", and perhaps some of the brand components can be repeated in "Composite" also, e.g., the global footer will show up in both "Brand + Design Elements -> Brand" and "Components -> Composite"?

@kerri-augenstein @sherakama please let me know if this would work.

**Comment by yvonnetangsu** [comment]
W

> Could we place the components for the
> 
> * brand bar
> * local header
> * local footer
> * global footer
> 
> on this page

Probably those 4 + logo and lockup, so 6 total.

**Comment by buttonwillowsix** [comment]
@kerri-augenstein  and @yvonnetangsu For the time being, I moved the brand bar, etc to this page, copying over what was in the Brand Compliance page. I wonder if this could let us shorten up the Brand Compliance page and point to this page for that section?

**Comment by yvonnetangsu** [comment]
@buttonwillowsix That sounds good to me!

**Comment by buttonwillowsix** [comment]
@kerri-augenstein was re-reviewing this tonight and I hadn't done the shortening up of the Brand Compliance page. Maybe we can spend some quick time moving things around in the AM?
