### ISSUE TITLE
Replace "@elseif" with "@else if" in Sass code

### ISSUE THREAD

**Issue by nrambeck** [SU-SWS/decanter#598]
**Describe the bug**

The latest version of Dart Sass generates a deprecation warning when it finds `@elseif` in the Decanter code. Evidently `@elseif`will be removed in the future, in favor of the primary else syntax of `@else if`. 

```
WARNING on line 73, column 7 of node_modules/decanter/core/src/scss/utilities/mixins/animation/_fancy-hover.scss: 
@elseif is deprecated and will not be supported in future Sass versions.
Use "@else if" instead.
   ╷
73 │     } @elseif ($position == 'top') {
   │       ^^^^^^^
   ╵
```

**To Reproduce**
1. Install Dart Sass version 1.23.x
2. Compile Decanter Sass with Dart Sass
3. You should see a warning similar to the one in the description above

**Expected behavior**

Expect to have no deprecation warnings with the latest version of Dart Sass.

**Additional context**

This was discovered while working on new themes for the H&S Drupal platform. We want to use Dart Sass to leverage some of the latest features Sass has to offer. Our team is happy to create a pull request for this work, if desired.

More info about the deprecation change: https://github.com/sass/dart-sass/pull/317

**Comment by sherakama** [comment]
Thanks for this. We're also seeing it in the latest sass compiler as well. Definitely will do.

**Comment by sherakama** [comment]
PRs always welcome 😉
