### ISSUE TITLE
Change display-f font size and style

### ISSUE THREAD

**Issue by yvonnetangsu** [SU-SWS/decanter#603]
**Is your feature request related to a problem? Please describe.**
Change the display-f mixin font size from 0.8em to 0.9em and remove the all caps text transform which allows for more flexibility and is easier to read as suggested by @kerri-augenstein .

**Comment by yvonnetangsu** [comment]
@kerri-augenstein Just want to confirm with you that this change will affect our hero and card components since they both use the @display-f mixin. Is this ok?

**Comment by kerri-augenstein** [comment]
@yvonnetangsu yes! i would love that!

**Comment by yvonnetangsu** [comment]
@kerri-augenstein pull request is up - please take a look. 
https://github.com/SU-SWS/decanter/pull/609
Just follow the links in "Steps to Test" :)

**Comment by yvonnetangsu** [comment]
Done
