### ISSUE TITLE
Tweak .su-big-paragraph style

### ISSUE THREAD

**Issue by kerri-augenstein** [SU-SWS/decanter#607]
After thinking more... let's make these two tweaks: 

font-size: 2.1rem; 
line-height: 1.7em; 

_Here is the intended outcome:_ 

<img width="1431" alt="outcome" src="https://user-images.githubusercontent.com/26723613/72553290-8d7fbd00-3866-11ea-9f52-298274228816.png">

**Comment by yvonnetangsu** [comment]
@kerri-augenstein Are you sure 2.1 not 2.2? :)

**Comment by kerri-augenstein** [comment]
@yvonnetangsu I thought about the 2.2rem A LOT. I think it is slightly big, but the 2.1 feels really nice. Think that's okay?

**Comment by yvonnetangsu** [comment]
And mobile is still 1.6rem, and 1.4 line height? Only 2 breakpoints?

**Comment by yvonnetangsu** [comment]
> @yvonnetangsu I thought about the 2.2rem A LOT. I think it is slightly big, but the 2.1 feels really nice. Think that's okay?

Oh we just posted at the same time. Yes!

**Comment by yvonnetangsu** [comment]
@kerri-augenstein And mobile is the same as before? 1.6rem and 1.4 line height?

**Comment by kerri-augenstein** [comment]
@yvonnetangsu that sounds great! yes! please :)

**Comment by yvonnetangsu** [comment]
Done
