### ISSUE TITLE
Change Display-type variable names

### ISSUE THREAD

**Issue by kerri-augenstein** [SU-SWS/decanter#618]
Instead of using letters to denote our Display A-F, let's revert to the numerals that correspond with the modular scale step to which the style coincides. 

add new = type-6 (_value of 6 in the modular steps_)
font-splash = type-5
type-a = type-4 
type-b = type-3
type-c = type-2
type-d = type-1
type-e = type-0 
type-f =  superhead??

**Comment by kerri-augenstein** [comment]
@yvonnetangsu, how does this look? And do I need to throw in a note about the type-5 needing to get the right modular scaling applied? Or maybe that's already done with the subset.

**Comment by sherakama** [comment]
I like this. Please take the slow deprecation approach and plan to support the new names in version 6 with the old ones deprecated and out in version 7.

**Comment by kerri-augenstein** [comment]
@sherakama eagle eyes.

**Comment by yvonnetangsu** [comment]
@kerri-augenstein @sherakama Great - will do. I just remember hmm....we manually coded type-f (I think it's just 0.9em because we found modular-scale(-1) too small when we changed it from all caps to regular case. What should we call this mixin/class? keep it as "-1". This is probably the only step that's smaller than modular-scale(0) so we could even make an exception and call it something else instead of using type--1.

**Comment by yvonnetangsu** [comment]
Annnnd - when would you guys ideally want this done?

**Comment by kerri-augenstein** [comment]
@yvonnetangsu, we won't really be using Display F, so feel free to handle that however you think it the best solution. 

There isn't any rush on our end. I need to execute this in the Figma documentation as well.

**Comment by yvonnetangsu** [comment]
@kerri-augenstein Cool. I'll think of something. Card superheadlines currently uses display-f, but I don't think that'd affect you guys since no matter what's called, the value isn't going to change. I might be removing display-f out of the scale and call it something else in that case, since it doesn't follow our modular-scale.

**Comment by kerri-augenstein** [comment]
@yvonnetangsu  that sounds good. We could also refactor the cards to call Display E if we want as well. (for the record, I'm not crazy about having a type size at 14px on XL breakpoints anyway, it's incredibly difficult to read, and may not pass accessibility standards?)

**Comment by yvonnetangsu** [comment]
@kerri-augenstein It might be worth creating a .su-superheadline class or something since I can see that being used in various ways. If you could design it from scratch - what would it be like ideally (in terms of font sizes at various BPs/style/color etc)?

**Comment by yvonnetangsu** [comment]
Agree that display-f is way too small for anything these days.

**Comment by kerri-augenstein** [comment]
@yvonnetangsu how do you feel about purposing display-e (or whatever that modular number becomes now) instead of adding a "superheadline"? I'm thinking that once we change the labels to: 

type-0
type-1
type-2
type-3 

etc., that we may have what we want?

**Comment by yvonnetangsu** [comment]
> @yvonnetangsu how do you feel about purposing display-e (or whatever that modular number becomes now) instead of adding a "superheadline"? I'm thinking that once we change the labels to:
> 
> type-0
> type-1
> type-2
> type-3
> 
> etc., that we may have what we want?

Yeah, that might work and we can decide about that later. FYI display-e is modular-typography(0) right now so it's same size as body text which is 1em. Currently, superheadline is a tad smaller - 0.9em.

**Comment by kerri-augenstein** [comment]
@yvonnetangsu I think we could leave it as 0, so that we're sure the text is readable, BUT we can always tweak it once we see it cascading out. (Don't want it to look horsey!)

**Comment by yvonnetangsu** [comment]
@kerri-augenstein  - sounds good 😄 This is what it looks like right now with 0.9em. 
https://decanter.stanford.edu/component/composite-card/
I'm totally fine with it being 1em.

**Comment by kerri-augenstein** [comment]
@yvonnetangsu I think I prefer the superhead to be 1em. Which makes me wonder. Should we call type-1 for the superhead now, instead of it not calling an actual mixin? (Or maybe I'm misunderstanding that :D) 

Okay, so just to confirm, type-0 is set to 1.8rem. But. Maybe we do want that set to 0.9em. That way we'll still have something that's slightly smaller (though not used in any of our wysiwyg's). 

Whaddya think?

I'm going to start updating the Decanter Figma this week as well.
