### ISSUE TITLE
Add new Modular Spacer 10

### ISSUE THREAD

**Issue by kerri-augenstein** [SU-SWS/decanter#620]
Based on design discussions with Ishi, we'd like to add another level of spacer on the higher end. 

Modular spacer 10 with a multiplier of 12

<img width="940" alt="Screen Shot 2020-02-13 at 12 48 15 PM" src="https://user-images.githubusercontent.com/26723613/74463287-9fea1800-4e5f-11ea-819c-30ccf1c91c2d.png">

**Comment by kerri-augenstein** [comment]
@sherakama I added in this ticket, is it a good one for Jen? 

cc @buttonwillowsix

**Comment by sherakama** [comment]
Yeah, our modular typography and spacing has to be our least documented and most complicated system in Decanter. I think this would be a good task to get to know it.

**Comment by yvonnetangsu** [comment]
Done
