### ISSUE TITLE
Tweak XS-SM, MD breakpoints for su-masthead

### ISSUE THREAD

**Issue by kerri-augenstein** [SU-SWS/decanter#622]
**MD Breakpoint**

Before:
<img width="779" alt="MD-before" src="https://user-images.githubusercontent.com/26723613/74570670-ca64cf80-4f4a-11ea-80a3-4f0a07381cb1.png">

After:
<img width="779" alt="MD-after" src="https://user-images.githubusercontent.com/26723613/74570615-b4570f00-4f4a-11ea-8f24-13248cff5e7c.png">
```
.su-multi-menu__nav-toggle:after {
  margin-bottom: 4px;
}

.su-masthead .su-lockup {
  margin-bottom: 2.8rem;
}

.su-lockup__wordmark {
  font-size: 42px;
  line-height: .8em;
}

```
**XS-SM Breakpoint**

Before:
<img width="551" alt="SM-before" src="https://user-images.githubusercontent.com/26723613/74570689-d2247400-4f4a-11ea-96e2-a8b9ce02671e.png">

After:
<img width="549" alt="SM-after" src="https://user-images.githubusercontent.com/26723613/74570710-d781be80-4f4a-11ea-9537-da5ef171e62c.png">

```
.su-lockup__line1 {
  font-size: 2.2rem;
  margin-top: 5px;
}
```

**Comment by yvonnetangsu** [comment]
@kerri-augenstein As we discussed, I'm going to ask to get this into my next sprint which will start Feb 19, and because we have so many lockup versions, we might or might not limit the scope to adjusting the font size for only a few of the lockup variants in this ticket.

**Comment by kerri-augenstein** [comment]
@yvonnetangsu sounds great!!
