### ISSUE TITLE
Change mixin label for "subheading" to "subtitle"

### ISSUE THREAD

**Issue by kerri-augenstein** [SU-SWS/decanter#626]
Users are getting confused by the label "subheading" as they are unsure how to use it in conjunction with the html headings in the wysiwyg. 

I'm not going to pull it from the wysiwyg, but I'd like to use the label "subtitle" both in our Drupal product and also in Decanter for consistency.

**Comment by kerri-augenstein** [comment]
@yvonnetangsu how do you feel about this?

**Comment by kerri-augenstein** [comment]
@sherakama fyi, do you think this is a good idea? And if we do this, it will have downs-stream affects on our wysiwyg "subtitle" style yes?

**Comment by sherakama** [comment]
I don't have a problem with changing labels in our wysiwyg. Labels are easy. Changing the css class and the mixin name will require us to deprecate the existing one and change to the new one. This shouldn't be too bad.
