### ISSUE TITLE
Primary form buttons

### ISSUE THREAD

**Issue by buttonwillowsix** [SU-SWS/decanter#649]
**Design documentation** 
https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Decanter-Design-System?node-id=11478%3A15201

**Dev note:** 
Note: all padding-bottom in buttons should be slightly bigger than padding-top, so that the text sits optically, vertically centered (Figma’s auto-layout feature prevents us designers from building this inside these design mocks). 

[Link to ticket for Secondary buttons](https://github.com/SU-SWS/decanter/issues/718)

![Primary Button](https://user-images.githubusercontent.com/42845005/93519074-95ef3280-f8e2-11ea-8d43-e6a2bf5dbd35.jpg)

**Comment by kerri-augenstein** [comment]
@bhavikasolanki let's add that we want to include secondary button styles here as well. Those buttons should mimic the bordered buttons in the "Button Selection Controls" designs (blue border, blue text, no background). Will need to design the hover, focused, pressed, and disabled states for those.

**Comment by cjwest** [comment]
@kerri-augenstein,
Is this done:
https://github.com/SU-SWS/decanter/blob/v6/core/src/scss/utilities/mixins/button/_button-big.scss#L12
https://github.com/SU-SWS/decanter/blob/v6/core/src/scss/utilities/mixins/button/_button-primary.scss#L11
https://github.com/SU-SWS/decanter/blob/v6/core/src/scss/utilities/mixins/button/_button-secondary.scss#L12
