### ISSUE TITLE
Character counter depreciation ticker for text field with character limit

### ISSUE THREAD

**Issue by buttonwillowsix** [SU-SWS/decanter#652]
**Dev notes**
[text input field short](https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Decanter-Design-System?node-id=10694%3A292)

**Design documentation**
- Padding and margin should not use modular spacers
- Text should not use modular text styles

![Screen Shot 2020-09-16 at 3 58 16 PM](https://user-images.githubusercontent.com/42845005/93400787-7948f100-f835-11ea-87ba-c02a4cc6895b.png)

**Comment by bhavikasolanki** [comment]
Hi @kerri-augenstein, this is mentioned in ticket #707 and looks complete in the ["Text field short" frame in Figma](https://user-images.githubusercontent.com/26723613/90168924-d4d21b80-dd6b-11ea-94da-15124e065caa.jpg). Does this character counter (and the other things listed in that ticket) require further design or design documentation? TY!!

**Comment by kerri-augenstein** [comment]
@bhavikasolanki to my knowledge the character counter is all set, and to your point is documented in the #707 ticket, but let's ask @buttonwillowsix if the devs would prefer this to be split out to keep their tickets smaller, and easier to close?
