### ISSUE TITLE
Chips/Pills/Tags

### ISSUE THREAD

**Issue by buttonwillowsix** [SU-SWS/decanter#653]
**Needs design**:
- hover, focused, pressed states
- design documentation for all

Include hover, focused, and pressed states.

**Design documentation:**
https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Decanter-Design-System?node-id=8148%3A321

**Dev notes:**

![Chips:Slugs](https://user-images.githubusercontent.com/42845005/90711524-d319c380-e255-11ea-991c-a4b7e34717ce.png)

**Comment by kerri-augenstein** [comment]
@bhavikasolanki I think we'll want to spend a little more time in design on these, so let's keep this ticket assigned to you, and note that there is more design work that needs to happen here.

**Comment by yvonnetangsu** [comment]
dibs
