### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by buttonwillowsix** [SU-SWS/decanter#655]
**Needs design**
- @kerri-augenstein is this the same thing as the progress bar indicators, or is this something else, like page numbers? (sorry if this is another one of those things that is already designed and that I overlooked!)

**Comment by kerri-augenstein** [comment]
@hyperboy, question for you. Dena, Bhavika, and I are doing ticket inventory for forms. We know that we want to design for different form sections, broken up into "progress states" (very similar to pagination). But. Do we also want to design for literal pagination?
