### ISSUE TITLE
Information button

### ISSUE THREAD

**Issue by buttonwillowsix** [SU-SWS/decanter#660]
**Dev notes**
- In instances of “knockout” icons (where the inside of the icon is transparent in part, like the “i” here), apply white to the background.

- Focused and pressed states should apply stroke to the outside of the icon only.

**Design documentation**
https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Decanter-Design-System?node-id=12877%3A50

![Icon button (1)](https://user-images.githubusercontent.com/42845005/95240059-b7945900-07c0-11eb-98e7-840d6b63edca.jpg)

**Comment by rebeccahongsf** [comment]
dibs :D

**Comment by rebeccahongsf** [comment]
@bhavikasolanki did we have a specific name that we would like to call this Information/Icon button? 😄

**Comment by rebeccahongsf** [comment]
Checked in with @bhavikasolanki in regards to the naming of this button.
Final decision: `Information Button` 

So in SCSS class `su-button--info` or a variation of that.
