### ISSUE TITLE
Date picker

### ISSUE THREAD

**Issue by buttonwillowsix** [SU-SWS/decanter#661]
**Needs design**:
- hover, focused, and pressed states for month/year select list
- hover, focus, pressed, and disabled states for left and right arrow buttons
- hover, focused, and pressed states for Date selected
- design documentation for all except Cancel CTA and Done button

Include hover, focus, and pressed states for:
- day/month/year fields 
- "Pick a date" button
- month/year select list on calendar 
- dates on calendar
- "Cancel" CTA on calendar 
- "Done" button on calendar
- left and right arrow buttons (include disabled state in addition to ones above)

Include indicator for Today's Date.

**Design documentation:**
https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Decanter-Design-System?node-id=8148%3A321

**Dev notes:**
All states for date (day, month, year) input fields will be exactly the same as other text input fields (see ticket #707).
Similarly, "Cancel" CTA link states will behave as other CTA links (see #719), and "Done" and "Pick a date" button states will behave as other form buttons (see #649).

![Date picker](https://user-images.githubusercontent.com/42845005/90712416-d57d1d00-e257-11ea-957c-c5e2bab13bbf.png)

**Comment by kerri-augenstein** [comment]
@buttonwillowsix, this guy is definitely incomplete. Do you want to include this ticket with what we have so far? Or should we leave as a design ticket until we're able to complete fleshing this guy out?
