### ISSUE TITLE
Selector controls: On/off Toggle Switches

### ISSUE THREAD

**Issue by buttonwillowsix** [SU-SWS/decanter#666]
**Needs Design**:
- Pressed state
- Disabled state
- Design documentation for all states

Include hover, focused, pressed, and disabled states.
**Design documentation:**
https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Decanter-Design-System?node-id=8148%3A321

**Dev notes:**

![Switches](https://user-images.githubusercontent.com/42845005/90708843-a662ad80-e24f-11ea-982e-cd65a43306a4.png)

**Comment by kerri-augenstein** [comment]
@bhavikasolanki let's talk about your process for the items that we know we have more design work to complete on. I know you have a spreadsheet (just remembering this now :D ) with all tasks noted. I'm adding the "needs design" labels to the tickets that have outstanding design work, and adding you as an assignee. I think that's all we want to keep clean in these GIT tickets for now, until the design work is complete.

**Comment by sherakama** [comment]
dibs
