### ISSUE TITLE
Rename "Global Brand Bar" to "Global Identity Bar" 

### ISSUE THREAD

**Issue by kerri-augenstein** [SU-SWS/decanter#677]
In order to achieve compliance with the UComm office, we're avoiding the use of the word "brand" in all of our work in Identity. 

Replace "brand" in all instances on the decanter site here: 
https://decanter.stanford.edu/page/brand-design-elements-brand/

Re-name-space in code as well, replace "brand" with "identity".

**Comment by kerri-augenstein** [comment]
@yvonnetangsu how much work will it be for us to rename this component in the name-spacing?

**Comment by yvonnetangsu** [comment]
> @yvonnetangsu how much work will it be for us to rename this component in the name-spacing?

@kerri-augenstein - I think it shouldn't be too bad (just need the proper deprecation)

**Comment by sherakama** [comment]
We can 2 step this. We can change the user-facing labels on the website to remove `brand` today but the component itself will need to be deprecated and the change pushed into the next release.

**Comment by buttonwillowsix** [comment]
This is updated on the site. Now for other places....
