### ISSUE TITLE
Code comment is showing inside decanter web menu

### ISSUE THREAD

**Issue by katrialesser** [SU-SWS/decanter#679]
**Describe the bug**
The comment here in this file:
https://github.com/SU-SWS/decanter/blob/master/core/src/scss/utilities/index.scss
is showing inside decanter web menu. I'm not sure if this comment should be placed differently or if the decanter-web project needs to handle it differently, but starting the issue here where the comment comes form.

**To Reproduce**
1. Go to https://decanter.stanford.edu/docs/scss/index.html#mixin-mixin-modular-spacing
2. scroll down in the menu to the General > CSS section and you'll see a bunch of comments where the menu should be.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/12898896/81726058-fad1e200-9443-11ea-859d-35e0aa867f13.png)

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [Chrome]

**Additional context**

**Comment by sherakama** [comment]
Some of these we will get to and some of them we wont.
