### ISSUE TITLE
Long Text Input Field

### ISSUE THREAD

**Issue by buttonwillowsix** [SU-SWS/decanter#707]
**Long Text input field including:**
- label and focus state for label (#741) @kerri-augenstein I know 35 char. is the label length for short text input fields; is this also true for long text input fields?
@buttonwillowsix, no, I don't think the char limit should = 35 characters for the long text input field. Additionally, should the char limit be a "guideline" and not actually an imposed limit, as if we create surveys, the label my inherently become a question, and 35char invalid at that point. 
- help text (#740)
- focus state (#743)
- required indication (#739)
- optional indication (#739)
- in-field error (#738)
- in-field validation (#737)
- disabled (#736)
- leading icon (#735)
- trailing icon (#734)
- character counter (#652)

**Dev notes:** 
- Padding and margin should not use modular spacers 
- Text should not use modular text styles 
- If possible, limit the width of a long text field to 600px wide, so that the text inside your field doesn’t grow longer than 80 characters, the limit to an ideal reading line length for long text. 

**Design documentation:**
- [text input field long](https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Decanter-Design-System?node-id=10724%3A115)
<img width="764" alt="Text Field Long" src="https://user-images.githubusercontent.com/42845005/93400405-98934e80-f834-11ea-97dd-51256ac9c99c.png">

**Comment by kerri-augenstein** [comment]
@buttonwillowsix, design documentation added

**Comment by kerri-augenstein** [comment]
@buttonwillowsix this is ready for development review

**Comment by kerri-augenstein** [comment]
@buttonwillowsix this is ready for development review.

**Comment by kerri-augenstein** [comment]
duplicating above comment here: 
@buttonwillowsix, no, I don't think the char limit should = 35 characters for the long text input field. Additionally, should the char limit be a "guideline" and not actually an imposed limit, as if we create surveys, the label my inherently become a question, and 35char invalid at that point.

**Comment by bhavikasolanki** [comment]
TY @kerri-augenstein! Should I copy/paste your comment on the ticket we have for Short Text Input Fields, too, in case that is also a guideline?

**Comment by kerri-augenstein** [comment]
@bhavikasolanki yes! Sounds great!!
