### ISSUE TITLE
Create main navigation component (twig & sass)

### ISSUE THREAD

**Issue by sherakama** [SU-SWS/decanter#72]
Establish a single main menu component with 1 variant. Design file TBD.

**Comment by yvonnetangsu** [comment]
Based on Figma "Stanford Design Library" -> "Menus & Navigation", this main nav component will now have 3 variants - centered, left-aligned and right-aligned.
https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Stanford-Design-Library?node-id=1%3A31
