### ISSUE TITLE
Button Selection

### ISSUE THREAD

**Issue by bhavikasolanki** [SU-SWS/decanter#720]
_Note: see mocks in Figma for margins between buttons._ 

Question: Dev Note: can buttons be as wide as the widest button needed based on the text inside? Aka, “Selected Button” is the longest text, and determines how wide all buttons in the string would be. 

**Design Documentation:**
https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Decanter-Design-System?node-id=10726%3A700

![Screen Shot 2020-09-18 at 3 35 55 AM](https://user-images.githubusercontent.com/42845005/93588380-2ae44100-f960-11ea-8acb-89ec79a823cc.png)

**Comment by kerri-augenstein** [comment]
@bhavikasolanki maybe let's add screenshots with the spacers showing as well as when they are hidden, I think that'll help with clarity for the devs.

**Comment by kerri-augenstein** [comment]
@buttonwillowsix this is ready for development. Or at least, review from development.
