### ISSUE TITLE
Decrease modular spacing amounts for mobile screen sizes

### ISSUE THREAD

**Issue by katrialesser** [SU-SWS/decanter#724]
**Is your feature request related to a problem? Please describe.**
In xs and sm breakpoints / mobile screens, the modular spacing amounts are too big.

We have had requests to decrease the spacing amounts on mobile. Kerri Augenstein has mocked up proposed changes for the XS and SM breakpoints:

https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Decanter-Design-System?node-id=1%3A16

Yvonne K Tang has been researching an approach to these changes using a get-map scss method that provides more customizable spacing amounts, rather than a more linear set of spacing amounts. She is implementing that in Decanter V7, but we also need this fix to be done in decanter v6.

We will likely specify the update in decanter with this change as a minor version, like 6,1 to indicate that there are changes and that people will need to look at those spacing changes and determine if their own code/styles need to be adjusted in any way.

**Describe the solution you'd like**
We'd like to apply the get-map approach that Yvonne Tang is looking at for Decanter V7, and employ that on Decanter V6.

**Describe alternatives you've considered**
I also looked at adjusting the current function structure, adding a calculate-mobile-modular-spacing to be used alongside the calculate-modular-spacing function, but it is not as clean or straightforward as the get-map approach.

**Additional context**
Note that we explored doing this work for the ADAPT-funded Static Sites project but it is too big and requires more testing and time to get done.

**Comment by sherakama** [comment]
Switched to responsive spacing and a curated grid of space.
