### ISSUE TITLE
Error summary box

### ISSUE THREAD

**Issue by bhavikasolanki** [SU-SWS/decanter#726]
**Design documentation**
[Error summary box](https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Decanter-Design-System?node-id=12672%3A2604)

![Error summary box (1)](https://user-images.githubusercontent.com/42845005/95366914-ee35a680-0888-11eb-9b79-9899e73ff125.jpg)

**Comment by bhavikasolanki** [comment]
@kerri-augenstein this is ready to be labeled "Ready for Dev," yea?

**Comment by kerri-augenstein** [comment]
AH, nope, that's a great step for me to take when we're good to go, I'll add that to my process. Ready for dev!
