### ISSUE TITLE
Add a document link icon

### ISSUE THREAD

**Issue by katrialesser** [SU-SWS/decanter#750]
**Is your feature request related to a problem? Please describe.**
We want a document icon for pdf links and links to other documents.

**Describe the solution you'd like**
We want to add a su-link--document class.

**Describe alternatives you've considered**
We could do this in a subtheme, but multiple clients benefit, and it adds accessibility help.

**Design:**
<img width="281" alt="Screen Shot 2020-09-22 at 8 26 42 AM" src="https://user-images.githubusercontent.com/26723613/93881811-6444e580-fcad-11ea-9349-102465fa8f6e.png">

**Document CTA link design file:**
https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Decanter-Design-System?node-id=6759%3A11821

**Icon files for "Document":**
[PNG in this folder](https://drive.google.com/drive/folders/1QmUwnsEpKp6aMORPlxa8DsCiwSGlAK5r)
[SVG in this folder](https://drive.google.com/drive/folders/1V8kbLRRkdbPQJ9sZfy7IgTB1t2DQDU-u)

**Additional context**

**Comment by kerri-augenstein** [comment]
@katrialesser, I totally lied about having this icon in our pack. I swear Bhavika and I did in fact do an icon for document, but I think it got lost in the fray of the work we'd completed when refactoring.

**Comment by kerri-augenstein** [comment]
@katrialesser all set, added now!
