### ISSUE TITLE
Create sidebar navigation component (twig & sass)

### ISSUE THREAD

**Issue by sherakama** [SU-SWS/decanter#76]
Secondary navigation component typically found in the left sidebar.

**Notes:**
There are slight visual differences between this element, and the dropdown/mobile navigation. 
- No light gray single pixel borders in between nav items
- Level 1 text size should be 20px (instead of 18px) 
- I also don't think we need the extra padding to the left of the hover-state vertical border, as we do on mobile and on dropdowns.

_Please also see the color tweak to the main navigation and mobile navigation here: 
https://github.com/SU-SWS/decanter/issues/422_

Source: https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Stanford-Design-Library?node-id=2384%3A1177
<img width="355" alt="in-page_subnav_left-column" src="https://user-images.githubusercontent.com/26723613/59152206-8d385d00-8a0d-11e9-8097-a8a0fbf596c5.png">

In-page context for design:
<img width="722" alt="in-page-subnav_page-context" src="https://user-images.githubusercontent.com/26723613/59152209-a0e3c380-8a0d-11e9-9ae8-cc617f1d6673.png">

**Comment by sherakama** [comment]
"Sidebar design is similar to the mobile main menu."

**Comment by buttonwillowsix** [comment]
Maybe wait for Yvonne's branch with color mapping to be merged.

**Comment by yvonnetangsu** [comment]
Done .su-secondary-nav
