### ISSUE TITLE
Duplicate styles.

### ISSUE THREAD

**Issue by sherakama** [SU-SWS/decanter#925]
**Describe the bug**
See: https://github.com/SU-SWS/adapt-my-account/pull/1037/files#r1322004247

Pick one. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yvonnetangsu** [comment]
Closing this issue @sherakama since we didn't introduce the duplicate styles (eg, -su-mt-30 and su--mt-30) on our end, since it was just TW being backward compatible. We'll fix any inconsistencies in the projects itself 😄
